window.PM_DASHBOARD_DATA = {
  "title": "Summer 2027 PM / APM Recruiting",
  "sourceWorkbook": "Summer_2027_PM_APM_Targets_Carlo_Vellandi(1).xlsx",
  "snapshotDate": "2026-08-16",
  "generatedDate": "2026-08-17",
  "records": [
    {
      "Rank": 1,
      "Company": "Google",
      "Program / Role": "Associate Product Manager (APM) Internship",
      "Target Type": "Established APM program",
      "Status": "Monitor",
      "Window / Deadline": "US Summer 2027 window not published on official APM page as of 2026-08-16",
      "Location(s)": "TBD",
      "Work Style": "TBD",
      "Eligibility for You": "Potentially eligible; exact 2027 US internship posting not live",
      "Degree / Major Notes": "Exact degree requirements TBD when US internship opens",
      "Technical Knowledge Expected": "Product sense, analytics, technical fluency; role-specific coding/CS expectations must be checked",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 10,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 6.4,
      "Recruiting / Interview Notes": "Typically product sense + analytical/strategy + behavioral; exact 2027 intern process TBD",
      "Compensation": "TBD",
      "Why It Fits You": "Best pure PM brand + founder apprenticeship; your communication/product experimentation profile is differentiated",
      "Immediate Next Action": "Set job alert; manually check official APM page + Google Careers weekly starting now",
      "Human Check Needed": "Official page currently surfaces London graduate dates, not a US Summer 2027 intern window. Manually search Google Careers for “Associate Product Manager Intern” because postings can appear briefly.",
      "Official Source": "https://www.google.com/about/careers/applications/programs/apm/",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 2,
      "Company": "HubSpot",
      "Program / Role": "Associate Product Management (APM) Internship",
      "Target Type": "Established APM internship",
      "Status": "Opening soon",
      "Window / Deadline": "Internship applications open early each fall for the following year",
      "Location(s)": "US role-specific; exact 2027 APM location TBD",
      "Work Style": "Role-specific / HubSpot supports hybrid and remote roles",
      "Eligibility for You": "Likely eligible; exact 2027 APM posting not live yet",
      "Degree / Major Notes": "Historically broad-major friendly; verify exact posting",
      "Technical Knowledge Expected": "Product sense, customer empathy, analytics, cross-functional communication; technical fluency helpful, coding usually not the core bar",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 10,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 8.3,
      "Recruiting / Interview Notes": "Historical official HubSpot guidance: application review → recruiter phone interview → role-specific interviews; APM interviews may include product thinking",
      "Compensation": "TBD",
      "Why It Fits You": "Excellent match for your writing, customer thinking, management, AI experimentation and non-CS background",
      "Immediate Next Action": "Create HubSpot job alert; check Emerging Talent North America roles at least weekly in early fall",
      "Human Check Needed": "The Emerging Talent page gives the timing but not a live 2027 APM requisition yet.",
      "Official Source": "https://www.hubspot.com/careers/emerging-talent",
      "Secondary / Exact Posting": "https://www.hubspot.com/careers-blog/hubspot-internship-recruiting-101-tips-tricks-from-recruiters",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 3,
      "Company": "DoorDash",
      "Program / Role": "Product Management Internship",
      "Target Type": "University internship / PM target",
      "Status": "Opening soon",
      "Window / Deadline": "Summer internship applications usually open in the Fall; roles fill quickly",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Likely eligible when undergraduate PM role opens",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "Product sense, marketplace/business judgment, analytics, experimentation; SQL may help but exact bar is posting-specific",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 7.8,
      "Recruiting / Interview Notes": "Likely recruiter + product cases/analytics/behavioral; exact 2027 PM intern process not yet published",
      "Compensation": "TBD",
      "Why It Fits You": "Strong founder training: marketplace economics, fast execution, operations + product; maps well to your HSA/operator background",
      "Immediate Next Action": "Monitor university careers now; apply immediately when a Summer 2027 PM role appears",
      "Human Check Needed": "Official university page publishes timing but no exact 2027 PM internship posting was verified today.",
      "Official Source": "https://careers.doordash.com/university-careers/",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 4,
      "Company": "Microsoft",
      "Program / Role": "Product Management Internship",
      "Target Type": "Global university internship",
      "Status": "Monitor",
      "Window / Deadline": "Exact US Summer 2027 PM posting/window not verified; careers site is source of truth",
      "Location(s)": "US role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Eligible for Microsoft university internships generally; PM-specific requirements vary",
      "Degree / Major Notes": "No universal CS-major rule on global internship page; exact PM role may vary",
      "Technical Knowledge Expected": "Technical fluency, customer/product thinking, metrics, cross-functional execution; coding depth varies by team",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 5.8,
      "Recruiting / Interview Notes": "Role-specific; expect behavioral + product/analytical questions, with technical depth depending on team",
      "Compensation": "TBD",
      "Why It Fits You": "Elite tech platform; broad product exposure and strong path into startups/founding later",
      "Immediate Next Action": "Search Microsoft Careers for Product Management + Internship + United States; create alerts",
      "Human Check Needed": "Official university page confirms Product Management is an internship area but does not expose an exact US 2027 PM requisition today.",
      "Official Source": "https://careers.microsoft.com/v2/global/en/universityinternship",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 5,
      "Company": "TikTok",
      "Program / Role": "Product Manager Intern — Product Infrastructure (Account)",
      "Target Type": "Confirmed live 2027 role",
      "Status": "Live",
      "Window / Deadline": "Rolling; applications reviewed in submission order; apply early",
      "Location(s)": "San Jose, CA",
      "Work Style": "Not stated; in-person housing allowance may apply",
      "Eligibility for You": "Eligible: current undergraduate/master; 12-week full-time 2027",
      "Degree / Major Notes": "No major restriction in this posting",
      "Technical Knowledge Expected": "Data metrics, user research, experimentation, product lifecycle, stakeholder influence; data/PM tools preferred",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 8.4,
      "Recruiting / Interview Notes": "TikTok early careers may use online assessments for some roles, then interviews; exact PM sequence is role-specific",
      "Compensation": "$35/hour; possible housing allowance",
      "Why It Fits You": "One of the best verified live PM jobs for you: consumer product, metrics, user empathy, no CS-major requirement",
      "Immediate Next Action": "APPLY NOW. Note TikTok caps candidates at 2 applications across TikTok/affiliates globally.",
      "Human Check Needed": "Before submitting, manually inspect application form for work authorization and availability fields; clearly state Summer 2027 availability on resume as requested.",
      "Official Source": "https://lifeattiktok.com/search/7670009830602721589",
      "Secondary / Exact Posting": "https://lifeattiktok.com/earlycareers/ams",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 6,
      "Company": "Salesforce",
      "Program / Role": "Associate Product Manager (APM) Internship — Summer 2027",
      "Target Type": "Established APM internship",
      "Status": "Closed",
      "Window / Deadline": "Opened early July; 2027 internship deadline was July 24, 2026",
      "Location(s)": "San Francisco, CA",
      "Work Style": "TBD / role-specific",
      "Eligibility for You": "Was a relevant rising-senior APM target; now closed",
      "Degree / Major Notes": "Verify archived exact posting if needed",
      "Technical Knowledge Expected": "Product strategy, user needs, data, cross-functional work; AI product context; moderate technical fluency",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 0.0,
      "Recruiting / Interview Notes": "APM program has dedicated interview prep/Trailhead; exact closed 2027 process can be reviewed via program page",
      "Compensation": "Reported $55–$59/hour in 2027 posting",
      "Why It Fits You": "Excellent benchmark for the type of role you should target; unfortunately this cycle's internship closed",
      "Immediate Next Action": "No action for Summer 2027 unless it reopens; keep full-time APM on future list",
      "Human Check Needed": "You can manually inspect Salesforce APM program page and set alerts in case another APM internship requisition appears.",
      "Official Source": "https://www.salesforce.com/company/careers/university/associate-program-manager/",
      "Secondary / Exact Posting": "https://www.linkedin.com/jobs/view/summer-2027-intern-associate-product-manager-apm-at-salesforce-4440369294",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 7,
      "Company": "Duolingo",
      "Program / Role": "Associate Product Manager Internship",
      "Target Type": "APM target / monitor",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 APM internship window not verified on official site today",
      "Location(s)": "TBD",
      "Work Style": "TBD",
      "Eligibility for You": "Potentially eligible; exact 2027 posting must be checked",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "Consumer product sense, experimentation, metrics, growth; technical fluency likely valued",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 5.8,
      "Recruiting / Interview Notes": "Expect product sense, analytics, behavioral; exact internship process TBD",
      "Compensation": "TBD",
      "Why It Fits You": "Consumer app + experimentation culture; strong fit with your media/product instincts and love of user-facing ideas",
      "Immediate Next Action": "Monitor Duolingo careers weekly for APM/Product Manager Intern",
      "Human Check Needed": "Official careers page is accessible, but an exact 2027 APM internship requisition was not verified. Search the live job board manually.",
      "Official Source": "https://careers.duolingo.com/",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 8,
      "Company": "Airbnb",
      "Program / Role": "Product Management Internship",
      "Target Type": "Internship program / PM target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM role/window not verified today",
      "Location(s)": "TBD; verify internship posting",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; exact posting TBD",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "Consumer marketplace product, user research, metrics, experimentation, cross-functional execution; AI prototyping increasingly valued",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 6.1,
      "Recruiting / Interview Notes": "Likely product cases + analytical + behavioral; exact intern process TBD",
      "Compensation": "TBD",
      "Why It Fits You": "Exceptional founder apprenticeship in marketplace/product; strong ownership-path value",
      "Immediate Next Action": "Monitor Airbnb Internship Programs + job search for Product Manager Intern",
      "Human Check Needed": "The internship program is official, but no exact 2027 PM internship was verified today.",
      "Official Source": "https://careers.airbnb.com/internship-programs/",
      "Secondary / Exact Posting": "https://careers.airbnb.com/positions/8104444/",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 9,
      "Company": "Roblox",
      "Program / Role": "Product Management Internship",
      "Target Type": "Early-career PM target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM requisition not verified today",
      "Location(s)": "TBD / role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; verify exact posting",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "Consumer product, metrics, experimentation, platform thinking; technical understanding important",
      "Tech Bar (1-5)": 4,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 5.9,
      "Recruiting / Interview Notes": "Official early-career material includes product-management assessment categories; technical applications may receive coding assessments",
      "Compensation": "TBD",
      "Why It Fits You": "High-upside consumer platform; product judgment and young-user ecosystem exposure could be excellent founder prep",
      "Immediate Next Action": "Monitor Roblox Early Career jobs and search Product Manager Intern weekly",
      "Human Check Needed": "Official early-career page discusses PM assessments but does not currently expose a specific 2027 PM internship.",
      "Official Source": "https://careers.roblox.com/early-career",
      "Secondary / Exact Posting": "https://careers.roblox.com/interviewing-at-roblox",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 10,
      "Company": "Adobe",
      "Program / Role": "Product Management / Product Internship",
      "Target Type": "University internship target",
      "Status": "Opening soon",
      "Window / Deadline": "Summer 2027 internship opportunities release on a rolling basis beginning early September 2026",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Likely eligible for non-engineering product roles; exact posting decides",
      "Degree / Major Notes": "Role-specific",
      "Technical Knowledge Expected": "Product sense, creative/user workflows, AI/product judgment, analytics; technical bar varies",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 7.6,
      "Recruiting / Interview Notes": "Role-specific; likely recruiter + product/behavioral + analytical depending team",
      "Compensation": "TBD",
      "Why It Fits You": "Large product portfolio + generative AI + strong consumer/creator products; very good fit with your media/AI experimentation",
      "Immediate Next Action": "Set reminder for first week of September; filter Adobe Careers for Internship + Product/Product Management",
      "Human Check Needed": "Exact Product Management internship title, location and degree requirements are not yet published.",
      "Official Source": "https://careers.adobe.com/us/en/event/6a0ccc369c6fc67e77b1defb/The-Intern-Legacy",
      "Secondary / Exact Posting": "https://careers.adobe.com/us/en/university",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 11,
      "Company": "American Express",
      "Program / Role": "2027 Undergraduate Product Internships (Digital Labs / GCS / ESS / Product Innovation)",
      "Target Type": "Confirmed live 2027 roles",
      "Status": "Live",
      "Window / Deadline": "Live now; US undergraduate recruiting generally runs Aug–Sep — apply early",
      "Location(s)": "New York, NY for multiple verified product roles",
      "Work Style": "Hybrid on several postings",
      "Eligibility for You": "Eligible rising senior undergraduate; exact role-specific requirements apply",
      "Degree / Major Notes": "Generally broad-major friendly; verify each requisition",
      "Technical Knowledge Expected": "Product strategy, analytics, customer journeys, payments/fintech; Excel/data comfort; no universal coding requirement",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 8.4,
      "Recruiting / Interview Notes": "US internship process generally includes pre-recorded behavioral video + interviews; tech roles may add technical assessment",
      "Compensation": "Role-specific",
      "Why It Fits You": "Very strong fit: business + product without CS-major gate; fintech/payments is useful for future entrepreneurship and capital literacy",
      "Immediate Next Action": "Open the current Product search and apply to the 1–2 product tracks that best fit your story",
      "Human Check Needed": "There are multiple live product postings; compare exact responsibilities before choosing. Do not shotgun every Amex role.",
      "Official Source": "https://careers.americanexpress.com/en/sites/CX_1/jobs?keyword=product+manager+intern&mode=location",
      "Secondary / Exact Posting": "https://careers.americanexpress.com/en/sites/CX_1/job/26011918/",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 12,
      "Company": "PayPal",
      "Program / Role": "Product Management Summer Internship",
      "Target Type": "North America university internship",
      "Status": "Monitor",
      "Window / Deadline": "US/Canada recruitment season runs August–March; applications considered on an ongoing basis",
      "Location(s)": "US/Canada role-specific",
      "Work Style": "Role-specific / relocation unless specified otherwise",
      "Eligibility for You": "Likely eligible: must return to school after internship and have work authorization",
      "Degree / Major Notes": "Exact PM posting decides",
      "Technical Knowledge Expected": "Payments/fintech product, analytics, customer experience, cross-functional execution; technical depth role-specific",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.8,
      "Recruiting / Interview Notes": "Role-specific; likely recruiter + product/behavioral/analytics",
      "Compensation": "TBD",
      "Why It Fits You": "Excellent non-CS PM path with fintech exposure; close to both product-building and business economics",
      "Immediate Next Action": "Search PayPal jobs for Product Management + Internship now and check weekly through fall",
      "Human Check Needed": "Official university page confirms Product Management is an internship area and season is Aug–Mar, but exact 2027 US PM requisition needs manual search.",
      "Official Source": "https://careers.pypl.com/university-hiring/north-america-latin-america/default.aspx",
      "Secondary / Exact Posting": "https://careers.pypl.com/categories/product-management/",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 13,
      "Company": "Figma",
      "Program / Role": "Product Management Internship",
      "Target Type": "High-upside watchlist employer",
      "Status": "Monitor",
      "Window / Deadline": "No Summer 2027 PM internship verified today",
      "Location(s)": "TBD; check live posting",
      "Work Style": "TBD",
      "Eligibility for You": "Unknown until posting exists",
      "Degree / Major Notes": "Unknown",
      "Technical Knowledge Expected": "Product craft, design collaboration, user research, technical fluency, SaaS/creator workflows",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 6.1,
      "Recruiting / Interview Notes": "Likely product sense + craft + behavioral/analytical; exact internship process unknown",
      "Compensation": "TBD",
      "Why It Fits You": "World-class product culture and founder-relevant product craft; especially attractive if a non-CS PM intern opens",
      "Immediate Next Action": "Monitor Figma careers; search 'Product' + 'Intern' and set alert",
      "Human Check Needed": "Current early-career openings did not show a PM internship. If you see one in the browser, send it to me immediately.",
      "Official Source": "https://www.figma.com/careers/",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 14,
      "Company": "Notion",
      "Program / Role": "Product Management Internship",
      "Target Type": "High-upside watchlist employer",
      "Status": "Monitor",
      "Window / Deadline": "No Summer 2027 PM internship verified today",
      "Location(s)": "TBD; exact internship location TBD",
      "Work Style": "Role-specific",
      "Eligibility for You": "Unknown until posting exists",
      "Degree / Major Notes": "Unknown",
      "Technical Knowledge Expected": "Product craft, workflow design, AI, qualitative user judgment, metrics; technical fluency valuable",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 6.1,
      "Recruiting / Interview Notes": "Likely product sense + execution/behavioral; exact internship process unknown",
      "Compensation": "TBD",
      "Why It Fits You": "Very strong founder/product apprenticeship if an intern role exists; directly aligned with your interest in tools/AI/workflows",
      "Immediate Next Action": "Monitor Notion careers for Product/PM internship; do not assume they run one every year",
      "Human Check Needed": "Official careers page currently shows early-career technical roles but no verified PM internship.",
      "Official Source": "https://www.notion.com/careers",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 15,
      "Company": "Intuit",
      "Program / Role": "Product Management Internship",
      "Target Type": "University product target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 US PM internship not verified today",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; exact posting TBD",
      "Degree / Major Notes": "Role-specific; non-CS PM roles may exist",
      "Technical Knowledge Expected": "Customer discovery, experimentation, fintech/small-business economics, analytics, AI/product judgment",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.7,
      "Recruiting / Interview Notes": "Likely product case + analytics + behavioral; exact role process TBD",
      "Compensation": "TBD",
      "Why It Fits You": "Strong mix of fintech, AI and small-business products; good bridge between PM and your future ownership ambitions",
      "Immediate Next Action": "Check Intuit interns/new grads with Product Management filter weekly",
      "Human Check Needed": "The product category exists, but no exact US Summer 2027 PM internship was verified in the current listings.",
      "Official Source": "https://jobs.intuit.com/interns-new-college-grads",
      "Secondary / Exact Posting": "https://jobs.intuit.com/category/product-management-jobs/",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 16,
      "Company": "Spotify",
      "Program / Role": "Global Summer Internship — Product / Product Management",
      "Target Type": "Global internship program",
      "Status": "Monitor",
      "Window / Deadline": "2027 application dates not published; 2026 cycle is closed",
      "Location(s)": "2027 TBD",
      "Work Style": "Role-specific",
      "Eligibility for You": "Likely eligible as penultimate-year student when 2027 opens; exact role TBD",
      "Degree / Major Notes": "Role-specific",
      "Technical Knowledge Expected": "Consumer product sense, experimentation, user/creator empathy, metrics, cross-functional leadership",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Role-specific; expect product/analytics/behavioral for PM-type roles",
      "Compensation": "TBD",
      "Why It Fits You": "Excellent consumer product training and brand; highly relevant to your media/product instincts",
      "Immediate Next Action": "Monitor Students page; Spotify does not accept late applications, so apply within the published window",
      "Human Check Needed": "Official Students page currently only states that 2026 applications are closed; 2027 dates are not yet posted.",
      "Official Source": "https://www.lifeatspotify.com/start-your-journey/students",
      "Secondary / Exact Posting": "https://www.lifeatspotify.com/find-your-team/job-categories/product",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 17,
      "Company": "Dedalus Labs",
      "Program / Role": "Product Manager Intern",
      "Target Type": "Startup PM target",
      "Status": "Human verify",
      "Window / Deadline": "A PM Intern role is surfaced by job indexes; exact Summer 2027 dates/deadline not accessible in current official careers page",
      "Location(s)": "San Francisco, CA",
      "Work Style": "Likely startup/in-person; verify",
      "Eligibility for You": "Possible fit, but technical expectations may be a hurdle",
      "Degree / Major Notes": "Official careers says strong technical foundation/CS-related coursework or degree preferred; exact internship requirement must be checked",
      "Technical Knowledge Expected": "AI agents/infrastructure, technical product, high agency; likely substantially more technical than consumer PM",
      "Tech Bar (1-5)": 4,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 7.4,
      "Recruiting / Interview Notes": "Startup-specific; likely founder/team interviews + product/technical depth",
      "Compensation": "TBD",
      "Why It Fits You": "Tiny AI company could be exceptional founder training and ownership exposure if they accept a non-CS candidate",
      "Immediate Next Action": "Open official careers → Ashby Job Board → locate Product Manager Intern; verify 2027 timing + degree requirement before applying",
      "Human Check Needed": "This is exactly a case where your browser may expose details my crawler cannot. Check the Ashby posting yourself.",
      "Official Source": "https://www.dedaluslabs.ai/careers",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 18,
      "Company": "Capital One",
      "Program / Role": "Product Development Internship Program (PDP)",
      "Target Type": "Established product internship",
      "Status": "Closed",
      "Window / Deadline": "2027 Product Development internship not currently listed; prior cycle appears to have closed",
      "Location(s)": "US role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "General internship eligibility supports students graduating by Aug 2028; exact PDP cycle closed/not listed",
      "Degree / Major Notes": "Economics is explicitly recognized as quantitative/STEM-related for some product early-career programs",
      "Technical Knowledge Expected": "Product strategy, business/analytics, customer problems; low coding requirement relative to technical PM",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 0.0,
      "Recruiting / Interview Notes": "Typically case/product-style and behavioral; exact 2027 closed-process details should be checked if it reopens",
      "Compensation": "TBD",
      "Why It Fits You": "One of the best non-CS product programs for you: analytical/business PM with strong training",
      "Immediate Next Action": "Set Capital One job alert; watch for a reopen or location-specific PDP requisition",
      "Human Check Needed": "Official internship page does not currently list the Product Development Internship. If your browser/Handshake shows a live PDP link, send it to me.",
      "Official Source": "https://www.capitalonecareers.com/internship-programs",
      "Secondary / Exact Posting": "https://www.capitalonecareers.com/get-ahead-with-early-career-programs-for-students",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 19,
      "Company": "Dropbox",
      "Program / Role": "Product Management Internship",
      "Target Type": "Emerging talent / PM watchlist",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM opening/window not verified today; general internship is 12 weeks",
      "Location(s)": "Role-specific",
      "Work Style": "Virtual First company model; intern specifics vary",
      "Eligibility for You": "Potentially eligible; exact role TBD",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "SaaS/product craft, collaboration, metrics, user workflows; technical fluency helpful",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.3,
      "Recruiting / Interview Notes": "Role-specific; likely product/behavioral/analytics",
      "Compensation": "TBD",
      "Why It Fits You": "Good PM craft + modern SaaS environment; flexible location can be attractive",
      "Immediate Next Action": "Monitor Emerging Talent and search Product + Intern",
      "Human Check Needed": "Official emerging-talent page confirms internship program but no exact 2027 PM requisition was verified today.",
      "Official Source": "https://www.dropbox.jobs/en/emerging-talent/",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 20,
      "Company": "IBM",
      "Program / Role": "Product Manager Intern 2027",
      "Target Type": "Confirmed live role — details partly blocked",
      "Status": "Human verify",
      "Window / Deadline": "Live now; posted mid-August 2026; exact deadline inaccessible to crawler",
      "Location(s)": "HUMAN VERIFY on official requisition",
      "Work Style": "HUMAN VERIFY",
      "Eligibility for You": "Likely relevant, but exact degree/eligibility details need manual inspection",
      "Degree / Major Notes": "Official page is JS/anti-bot blocked; inspect exact education/technical requirements yourself",
      "Technical Knowledge Expected": "AI-enabled/data-driven software, research, experimentation, prioritization, stakeholder collaboration",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 7.0,
      "Recruiting / Interview Notes": "Likely PM/product + behavioral + analytical; exact process TBD",
      "Compensation": "HUMAN VERIFY",
      "Why It Fits You": "Real live 2027 PM title at a major tech company; could be a very good non-obvious option if no CS-major gate",
      "Immediate Next Action": "OPEN THE OFFICIAL ROLE IN YOUR BROWSER NOW; verify location, major restriction and deadline. If eligible, apply promptly.",
      "Human Check Needed": "The official IBM page requires JavaScript/anti-bot verification, so you can see facts I cannot. This is a priority human check.",
      "Official Source": "https://careers.ibm.com/en_US/careers/JobDetail/Product-Manager-Intern-2027/128509",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 21,
      "Company": "Mastercard",
      "Program / Role": "Product Management Internship",
      "Target Type": "Global internship / product target",
      "Status": "Monitor",
      "Window / Deadline": "Internships recruited on a rolling basis; exact US 2027 PM requisition not verified today",
      "Location(s)": "US/global role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Likely eligible as enrolled Bachelor's student; exact role decides",
      "Degree / Major Notes": "Generally business/product friendly; exact major TBD",
      "Technical Knowledge Expected": "Payments product, business cases, roadmaps, launch, analytics; limited coding likely for business PM",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Role-specific; likely behavioral + product/business case",
      "Compensation": "TBD",
      "Why It Fits You": "Payments + product is useful for both founder skills and financial-system understanding",
      "Immediate Next Action": "Search Mastercard Product Management jobs + Internship + United States now; check regularly because rolling",
      "Human Check Needed": "Official internship and PM pages exist, but the exact Summer 2027 US PM role needs manual job search.",
      "Official Source": "https://careers.mastercard.com/us/en/early-careers/internships",
      "Secondary / Exact Posting": "https://careers.mastercard.com/us/en/c/product-management-jobs",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 22,
      "Company": "eBay",
      "Program / Role": "Product Management Internship",
      "Target Type": "Emerging talent / marketplace PM target",
      "Status": "Opening soon",
      "Window / Deadline": "Internship roles are posted September through March",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; exact 2027 PM posting TBD",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "Marketplace product, growth, seller/buyer experience, analytics, experimentation",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 7.0,
      "Recruiting / Interview Notes": "Role-specific; likely product + analytics + behavioral",
      "Compensation": "TBD",
      "Why It Fits You": "Marketplace PM is founder-relevant and fits your interest in consumer products and business models",
      "Immediate Next Action": "Start checking in early September; set eBay Emerging Talent alert",
      "Human Check Needed": "Official page gives posting season but not a live 2027 PM requisition yet.",
      "Official Source": "https://jobs.ebayinc.com/us/en/emerging-talent",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 23,
      "Company": "Lyft",
      "Program / Role": "Product Management Internship",
      "Target Type": "Early talent / marketplace PM target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM opening/window not verified today",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; exact posting TBD",
      "Degree / Major Notes": "TBD",
      "Technical Knowledge Expected": "Marketplace product, rider/driver problems, experimentation, metrics, operations + product",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Role-specific; likely product case + metrics + behavioral",
      "Compensation": "TBD",
      "Why It Fits You": "Strong marketplace/founder training; your operations background could translate well",
      "Immediate Next Action": "Monitor Lyft Early Talent and Product job filters",
      "Human Check Needed": "Official early-talent page is live, but no exact 2027 PM intern posting was verified today.",
      "Official Source": "https://www.lyft.com/careers/early-talent",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 24,
      "Company": "Reddit",
      "Program / Role": "Product Management Internship",
      "Target Type": "Consumer product watchlist",
      "Status": "Monitor",
      "Window / Deadline": "Current Summer 2027 PM role not verified; Reddit has historically run PM internships",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Unknown until role appears",
      "Degree / Major Notes": "TBD",
      "Technical Knowledge Expected": "Community product, moderation/growth, experimentation, metrics, qualitative user behavior",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Likely product sense + analytics + behavioral",
      "Compensation": "TBD",
      "Why It Fits You": "Consumer/community product is a natural fit with Dad Lore and your interest in social products",
      "Immediate Next Action": "Monitor Reddit careers for Product + Intern; do not assume a PM internship will exist this cycle",
      "Human Check Needed": "Current careers page is source of truth; historical PM internship existence does not guarantee a 2027 opening.",
      "Official Source": "https://redditinc.com/careers",
      "Secondary / Exact Posting": "https://redditinc.com/news/announcing-season-2-of-reddits-internship-program",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 25,
      "Company": "Walmart",
      "Program / Role": "Product Management Internship",
      "Target Type": "Undergraduate internship / product target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM role/window not verified today",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; official student site includes Product Management as a career area",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "Large-scale commerce product, customer/associate tools, data, roadmap prioritization",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Role-specific; likely behavioral + product/business case",
      "Compensation": "TBD",
      "Why It Fits You": "Massive real-world product scale and commerce economics; less glamorous but strong operating training",
      "Immediate Next Action": "Use Walmart Students → Product Management → See opportunities; filter internships",
      "Human Check Needed": "Product Management is explicitly shown as a student career area, but exact 2027 requisition must be found manually.",
      "Official Source": "https://careers.walmart.com/us/en/home/careers-areas/students",
      "Secondary / Exact Posting": "https://careers.walmart.com/us/en/home/careers-areas/technology/product-management",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 26,
      "Company": "ServiceNow",
      "Program / Role": "Product Management Internship",
      "Target Type": "Early careers / enterprise product target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM requisition not verified today",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; exact posting TBD",
      "Degree / Major Notes": "Role-specific; technical depth can vary",
      "Technical Knowledge Expected": "Enterprise SaaS, AI/workflows, roadmap, customer problems, technical fluency",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.3,
      "Recruiting / Interview Notes": "Role-specific; likely product + behavioral + technical fluency",
      "Compensation": "TBD",
      "Why It Fits You": "Good enterprise SaaS/AI product apprenticeship; useful if you want to learn B2B software economics",
      "Immediate Next Action": "Search ServiceNow jobs with Posting Type Intern + AI/Engineering/Product",
      "Human Check Needed": "Official early-careers page confirms internships but no exact PM 2027 role was verified today.",
      "Official Source": "https://careers.servicenow.com/early-careers/",
      "Secondary / Exact Posting": "https://careers.servicenow.com/jobs/",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 27,
      "Company": "Snap",
      "Program / Role": "Product Management Internship",
      "Target Type": "Emerging talent / consumer product target",
      "Status": "Monitor",
      "Window / Deadline": "No current US Product intern verified today",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Unknown until posting exists",
      "Degree / Major Notes": "TBD",
      "Technical Knowledge Expected": "Consumer social product, experimentation, growth, creator/advertiser ecosystems, metrics",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Likely product sense + analytics + behavioral",
      "Compensation": "TBD",
      "Why It Fits You": "Strong consumer/social product training; directly adjacent to the kinds of products you like experimenting with",
      "Immediate Next Action": "Monitor Snap Emerging Talent; filter live jobs for Product + Intern weekly",
      "Human Check Needed": "Current job board did not show a US PM intern at verification time.",
      "Official Source": "https://careers.snap.com/emerging-talent",
      "Secondary / Exact Posting": "https://careers.snap.com/jobs",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 28,
      "Company": "Visa",
      "Program / Role": "Product Management Internship",
      "Target Type": "Early careers / fintech product target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM role/window not verified today",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; exact posting TBD",
      "Degree / Major Notes": "Generally product/business friendly; exact major TBD",
      "Technical Knowledge Expected": "Payments/network product, business cases, analytics, customer solutions, roadmap",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Role-specific; likely behavioral + business/product case",
      "Compensation": "TBD",
      "Why It Fits You": "Strong payments infrastructure exposure; useful business/product skillset even if less startup-like",
      "Immediate Next Action": "Search Visa jobs for Product Management + Intern + United States; create alert",
      "Human Check Needed": "Official early-career page exists, but exact 2027 PM posting must be located manually.",
      "Official Source": "https://corporate.visa.com/en/careers/early-careers.html",
      "Secondary / Exact Posting": "https://corporate.visa.com/en/jobs/",
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 29,
      "Company": "Databricks",
      "Program / Role": "Product Management Intern — Summer 2027",
      "Target Type": "Confirmed live 2027 role",
      "Status": "Live — likely ineligible",
      "Window / Deadline": "Live now",
      "Location(s)": "San Francisco / Mountain View, CA; Bellevue, WA",
      "Work Style": "Role-specific",
      "Eligibility for You": "Likely ineligible for you",
      "Degree / Major Notes": "Requires Bachelor's/Master's in Computer Science or related engineering; Fall 2027/Spring 2028 graduation",
      "Technical Knowledge Expected": "SQL/Python, AI tools, technical product, data/AI platform knowledge",
      "Tech Bar (1-5)": 5,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 4,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 0.0,
      "Recruiting / Interview Notes": "Technical/product interviews likely; exact process role-specific",
      "Compensation": "Bay Area $54–$56/hour; Bellevue $51.50–$53.50/hour",
      "Why It Fits You": "Elite PM training, but this exact posting's degree requirement is a hard mismatch with Econ/Philosophy",
      "Immediate Next Action": "Do NOT spend time applying unless the degree requirement changes or recruiter confirms your degree qualifies",
      "Human Check Needed": "You can read the degree requirement directly on the official posting.",
      "Official Source": "https://www.databricks.com/company/careers/product/product-management-intern-summer-2027-6883068002",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    },
    {
      "Rank": 30,
      "Company": "Appian",
      "Program / Role": "Product Manager Intern — Summer 2027",
      "Target Type": "Confirmed live 2027 role",
      "Status": "Live — likely ineligible",
      "Window / Deadline": "Live; recruiting/interview scheduling begins Aug 2026",
      "Location(s)": "McLean, VA",
      "Work Style": "Role-specific",
      "Eligibility for You": "Likely ineligible for you",
      "Degree / Major Notes": "Requires Bachelor's/Master's in Computer Science or Computer Engineering",
      "Technical Knowledge Expected": "AI/LLM fluency, technical product, software concepts; technical internship/projects preferred",
      "Tech Bar (1-5)": 5,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 3,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 0.0,
      "Recruiting / Interview Notes": "Product + technical interviews likely",
      "Compensation": "$50/hour (~$8,666/month)",
      "Why It Fits You": "Good PM role, but exact degree gate makes it a poor use of your time",
      "Immediate Next Action": "Skip unless recruiter explicitly says non-CS majors may apply",
      "Human Check Needed": "Degree requirement is explicit on official job posting.",
      "Official Source": "https://careers.appian.com/jobs/8041243-product-manager-intern-",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16"
    }
  ]
};
