window.PM_DASHBOARD_DATA = {
  "title": "Summer 2027 Product / APM / High-Upside Recruiting",
  "sourceWorkbook": "Summer_2027_PM_APM_Targets_Carlo_Vellandi.xlsx + live web refresh",
  "snapshotDate": "2026-08-19",
  "generatedDate": "2026-08-19",
  "records": [
    {
      "Rank": 1,
      "Company": "Jane Street",
      "Program / Role": "Strategy and Product Internship — May–August",
      "Target Type": "Elite adjacent product / strategy / finance-tech internship",
      "Status": "Live",
      "Window / Deadline": "Rolling; Jane Street encourages applying by September 30, 2026",
      "Location(s)": "New York, NY",
      "Work Style": "In person / role-specific",
      "Eligibility for You": "Eligible: pursuing Bachelor/advanced degree and available to start full-time September 2028",
      "Degree / Major Notes": "No specific major or finance background required; firm emphasizes how candidates think and learn",
      "Technical Knowledge Expected": "Structured analytical problem solving, data, business frameworks, technical systems/tooling, operational infrastructure; technical fluency helpful but not a CS gate",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 10,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 9.9,
      "Recruiting / Interview Notes": "Very high-bar generalist internship. Prepare structured problem solving, estimation/analytical reasoning, project ownership, and ability to learn across markets/technology/operations.",
      "Compensation": "$225,000 annualized base salary (intern pay prorated)",
      "Why It Fits You": "Exceptional prestige/pay plus broad strategy/product exposure at the intersection of markets, technology, and operations. Directly relevant to your broader money + optionality + future ownership goals.",
      "Immediate Next Action": "APPLY NOW — this is not “PM or bust”; it is one of the strongest live adjacent opportunities for your actual objectives.",
      "Human Check Needed": "Confirm application asks for September 2028 full-time availability and prepare for Jane Street-specific interview format.",
      "Official Source": "https://www.janestreet.com/join-jane-street/position/8621552002/",
      "Secondary / Exact Posting": "https://www.janestreet.com/join-jane-street/position/8621552002/",
      "Last Verified": "2026-08-19",
      "Applications": [
        {
          "id": "8621552002",
          "title": "Strategy and Product Internship — May–August",
          "roleStatus": "Live",
          "jobId": "8621552002",
          "deadline": "Apply by Sep. 30 encouraged; rolling",
          "location": "New York, NY",
          "workStyle": "In person / role-specific",
          "compensation": "$225,000 annualized base (prorated for internship)",
          "url": "https://www.janestreet.com/join-jane-street/position/8621552002/",
          "description": "STRATEGY AND PRODUCT INTERNSHIP — MAY–AUGUST\n\nABOUT THE ROLE\nStrategy & Product interns work on projects that combine big-picture thinking with rigorous analytical problem solving. Interns break complex challenges into actionable steps, use data to inform decisions, build frameworks for business questions, and gain direct exposure to strategic initiatives across Jane Street.\n\nThe Strategy & Product function spans firmwide problems and can touch global markets, technical systems and tooling, and operational infrastructure. Jane Street's prior description notes that this internship combines the firm's previous Business Development and Tech PM internships.\n\nCANDIDATE PROFILE\n• Structured, careful problem solver with strong communication, project ownership, and attention to detail.\n• Excited to learn across global market dynamics, technical systems/tooling, operational infrastructure, and other disciplines.\n• Eager to ask questions, learn quickly, and deepen understanding.\n• Currently pursuing a Bachelor's degree, MBA, or another advanced degree.\n• Available to start full-time in September 2028.\n\nPROCESS / TIMING\nApplications are reviewed on a rolling basis. Jane Street says it plans to remain open through the fall and encourages applying by September 30.\n\nLOCATION / COMPENSATION\nNew York City. Published annualized base salary: $225,000 (intern pay is prorated for the internship period).",
          "descriptionSource": "Official Jane Street posting captured 2026-08-19",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 2,
      "Company": "Google",
      "Program / Role": "Associate Product Manager (APM) Internship",
      "Target Type": "Established APM program",
      "Status": "Monitor",
      "Window / Deadline": "US Summer 2027 window not published on official APM page as of 2026-08-16",
      "Location(s)": "TBD",
      "Work Style": "TBD",
      "Eligibility for You": "Potentially eligible; exact 2027 US internship posting not live",
      "Degree / Major Notes": "Exact degree requirements TBD when US internship opens",
      "Technical Knowledge Expected": "Product sense, analytics, technical fluency; role-specific coding/CS expectations must be checked",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 10,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 6.4,
      "Recruiting / Interview Notes": "Typically product sense + analytical/strategy + behavioral; exact 2027 intern process TBD",
      "Compensation": "TBD",
      "Why It Fits You": "Best pure PM brand + founder apprenticeship; your communication/product experimentation profile is differentiated",
      "Immediate Next Action": "Set job alert; manually check official APM page + Google Careers weekly starting now",
      "Human Check Needed": "Official page currently surfaces London graduate dates, not a US Summer 2027 intern window. Manually search Google Careers for “Associate Product Manager Intern” because postings can appear briefly.",
      "Official Source": "https://www.google.com/about/careers/applications/programs/apm/",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16",
      "Applications": []
    },
    {
      "Rank": 3,
      "Company": "Microsoft",
      "Program / Role": "Product Manager: Internship Opportunities — Summer 2027",
      "Target Type": "Confirmed live 2027 PM internship",
      "Status": "Live",
      "Window / Deadline": "Live now; applications processed on an ongoing basis until filled",
      "Location(s)": "Redmond, WA",
      "Work Style": "3 days/week in office",
      "Eligibility for You": "Eligible: current degree student with at least one academic term remaining after internship",
      "Degree / Major Notes": "CS/Engineering or related degree is preferred, not listed as a universal minimum requirement",
      "Technical Knowledge Expected": "Customer/market analysis, product vision/strategy, metrics and telemetry, roadmap prioritization, cross-functional product execution; moderate technical fluency",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 9.7,
      "Recruiting / Interview Notes": "Apply promptly; expect product sense, analytical/metrics, behavioral, and technical-fluency questions depending on team.",
      "Compensation": "$5,690–$11,210/month listed for Redmond band; location-dependent higher ranges may apply elsewhere",
      "Why It Fits You": "Elite tech PM brand and high-pay pathway; broad-major eligibility is plausible, while your product artifacts can offset the lack of a CS major.",
      "Immediate Next Action": "APPLY NOW — use PM resume; prepare product sense + metrics + technical-fluency stories.",
      "Human Check Needed": "Before submitting, confirm the current application form and exact internship availability dates; preferred technical-degree language is not a hard minimum in the posting.",
      "Official Source": "https://careers.microsoft.com/v2/global/en/students?jobSeqNo=1221013",
      "Secondary / Exact Posting": "https://careers.microsoft.com/v2/global/en/students?jobSeqNo=1221013",
      "Last Verified": "2026-08-19",
      "Applications": [
        {
          "id": "1221013",
          "title": "Product Manager: Internship Opportunities — Summer 2027",
          "roleStatus": "Live",
          "jobId": "1221013",
          "deadline": "Ongoing until filled",
          "location": "Redmond, WA",
          "workStyle": "3 days/week in office",
          "compensation": "$5,690–$11,210/month (Redmond band)",
          "url": "https://careers.microsoft.com/v2/global/en/students?jobSeqNo=1221013",
          "description": "PRODUCT MANAGER: INTERNSHIP OPPORTUNITIES — SUMMER 2027\n\nOVERVIEW\nAs a Product Manager Intern, define product vision and strategy using customer experience and competitive-market understanding; identify short- and long-term investment opportunities, evaluate tradeoffs, build consensus, and drive product roadmaps. The internship is based in Redmond and is scheduled for Summer 2027.\n\nRESPONSIBILITIES\n• Identify unmet or unknown customer needs and market opportunities using quantitative and qualitative analysis.\n• Define and track success criteria, Key Results, and performance metrics; partner with engineering so the right telemetry exists.\n• Prioritize roadmap features and experiences that support objectives and measurable outcomes.\n• Partner with design and engineering to define features, release criteria, and customer experiences.\n• Use customer feedback and product data to improve products after launch.\n\nQUALIFICATIONS\n• Pursuing a Bachelor's, Master's, or Doctorate degree with at least one academic term remaining after the internship.\n• Preferred qualifications include a degree in Computer Science, Engineering, or a related field and prior product/service/project/program-management or software-development experience; these are preferred rather than universal minimum gates.\n\nWORK STYLE / LOCATION\nRedmond, Washington; 3 days per week in office.\n\nCOMPENSATION\nPublished monthly range varies by work location; the Redmond posting lists an internship pay band and higher bands apply in SF/NYC.",
          "descriptionSource": "Official Microsoft posting captured 2026-08-19",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 4,
      "Company": "TikTok",
      "Program / Role": "Product Manager Intern — Product Infrastructure (Account)",
      "Target Type": "Confirmed live 2027 role",
      "Status": "Live",
      "Window / Deadline": "Rolling; applications reviewed in submission order; apply early",
      "Location(s)": "San Jose, CA",
      "Work Style": "Not stated; in-person housing allowance may apply",
      "Eligibility for You": "Eligible: current undergraduate/master; 12-week full-time 2027",
      "Degree / Major Notes": "No major restriction in this posting",
      "Technical Knowledge Expected": "Data metrics, user research, experimentation, product lifecycle, stakeholder influence; data/PM tools preferred",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 8.4,
      "Recruiting / Interview Notes": "TikTok early careers may use online assessments for some roles, then interviews; exact PM sequence is role-specific",
      "Compensation": "$35/hour; possible housing allowance",
      "Why It Fits You": "One of the best verified live PM jobs for you: consumer product, metrics, user empathy, no CS-major requirement",
      "Immediate Next Action": "Applied. Monitor portal/email; prepare for PM interview stages if contacted.",
      "Human Check Needed": "Before submitting, manually inspect application form for work authorization and availability fields; clearly state Summer 2027 availability on resume as requested.",
      "Official Source": "https://lifeattiktok.com/search/7670009830602721589",
      "Secondary / Exact Posting": "https://lifeattiktok.com/earlycareers/ams",
      "Last Verified": "2026-08-19",
      "Applications": [
        {
          "id": "A17812A",
          "title": "Product Manager Intern — TikTok Product Infrastructure (Account) — Summer 2027",
          "roleStatus": "Live",
          "jobId": "A17812A",
          "deadline": "Rolling / apply early",
          "location": "San Jose, CA",
          "workStyle": null,
          "compensation": "$35/hour; possible housing allowance",
          "url": "https://lifeattiktok.com/search/7670009830602721589",
          "description": "PRODUCT MANAGER INTERN — TIKTOK PRODUCT INFRASTRUCTURE (ACCOUNT), SUMMER 2027\n\nTEAM / ROLE\nProduct Infrastructure focuses on the systems and product foundations that help users create, consume, and enjoy TikTok content reliably, securely, and at scale. The internship is a 12-week Summer 2027 product role in San Jose.\n\nRESPONSIBILITIES\n• Define data metrics for product areas and use data, algorithms, research, and market analysis to inform product design and decisions.\n• Research user needs and translate findings into product improvements.\n• Drive continuous product iteration and experimentation.\n• Participate across the product lifecycle: ideation, design, build, test, launch, and post-launch measurement.\n• Work cross-functionally and influence stakeholders and leaders around priorities and product decisions.\n\nQUALIFICATIONS\n• Current undergraduate or master's student available for a 12-week full-time internship in 2027.\n• Strong communication and collaboration skills.\n• Empathy for users and creators and interest in consumer product experiences.\n• Preferred: experience with data analysis, user research, product-management tools, and creative product thinking.\n\nAPPLICATION NOTES\nTikTok caps candidates at two applications across TikTok and affiliates. Applications are reviewed on a rolling basis and the posting asks candidates to state exact Summer 2027 availability on the résumé.\n\nCOMPENSATION\n$35/hour; possible housing allowance depending on eligibility/location.",
          "descriptionSource": "Official posting + user-pasted application details captured 2026-08-18",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 5,
      "Company": "HubSpot",
      "Program / Role": "Associate Product Management (APM) Internship",
      "Target Type": "Established APM internship",
      "Status": "Opening soon",
      "Window / Deadline": "Internship applications open early each fall for the following year",
      "Location(s)": "US role-specific; exact 2027 APM location TBD",
      "Work Style": "Role-specific / HubSpot supports hybrid and remote roles",
      "Eligibility for You": "Likely eligible; exact 2027 APM posting not live yet",
      "Degree / Major Notes": "Historically broad-major friendly; verify exact posting",
      "Technical Knowledge Expected": "Product sense, customer empathy, analytics, cross-functional communication; technical fluency helpful, coding usually not the core bar",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 10,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 8.3,
      "Recruiting / Interview Notes": "Historical official HubSpot guidance: application review → recruiter phone interview → role-specific interviews; APM interviews may include product thinking",
      "Compensation": "TBD",
      "Why It Fits You": "Excellent match for your writing, customer thinking, management, AI experimentation and non-CS background",
      "Immediate Next Action": "Create HubSpot job alert; check Emerging Talent North America roles at least weekly in early fall",
      "Human Check Needed": "The Emerging Talent page gives the timing but not a live 2027 APM requisition yet.",
      "Official Source": "https://www.hubspot.com/careers/emerging-talent",
      "Secondary / Exact Posting": "https://www.hubspot.com/careers-blog/hubspot-internship-recruiting-101-tips-tricks-from-recruiters",
      "Last Verified": "2026-08-16",
      "Applications": [
        {
          "id": "hubspot-summer-2027",
          "title": "Associate Product Management (APM) Internship",
          "roleStatus": "Opening soon",
          "jobId": "TBD",
          "deadline": "Internship applications open early each fall for the following year",
          "location": "US role-specific; exact 2027 APM location TBD",
          "workStyle": "Role-specific / HubSpot supports hybrid and remote roles",
          "compensation": "TBD",
          "url": "https://www.hubspot.com/careers/emerging-talent",
          "description": "Exact Summer 2027 role description has not been captured yet. Current tracker status: Opening soon.\n\nWhen the posting goes live, paste the full description into ChatGPT and regenerate data.js so this panel becomes the complete application record.",
          "descriptionSource": "Program/role tracking stub; exact posting pending",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 6,
      "Company": "DoorDash",
      "Program / Role": "Product Management Internship",
      "Target Type": "University internship / PM target",
      "Status": "Opening soon",
      "Window / Deadline": "Summer internship applications usually open in the Fall; roles fill quickly",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Likely eligible when undergraduate PM role opens",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "Product sense, marketplace/business judgment, analytics, experimentation; SQL may help but exact bar is posting-specific",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 7.8,
      "Recruiting / Interview Notes": "Likely recruiter + product cases/analytics/behavioral; exact 2027 PM intern process not yet published",
      "Compensation": "TBD",
      "Why It Fits You": "Strong founder training: marketplace economics, fast execution, operations + product; maps well to your HSA/operator background",
      "Immediate Next Action": "Monitor university careers now; apply immediately when a Summer 2027 PM role appears",
      "Human Check Needed": "Official university page publishes timing but no exact 2027 PM internship posting was verified today.",
      "Official Source": "https://careers.doordash.com/university-careers/",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16",
      "Applications": [
        {
          "id": "doordash-summer-2027",
          "title": "Product Management Internship",
          "roleStatus": "Opening soon",
          "jobId": "TBD",
          "deadline": "Summer internship applications usually open in the Fall; roles fill quickly",
          "location": "Role-specific",
          "workStyle": "Role-specific",
          "compensation": "TBD",
          "url": "https://careers.doordash.com/university-careers/",
          "description": "Exact Summer 2027 role description has not been captured yet. Current tracker status: Opening soon.\n\nWhen the posting goes live, paste the full description into ChatGPT and regenerate data.js so this panel becomes the complete application record.",
          "descriptionSource": "Program/role tracking stub; exact posting pending",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 7,
      "Company": "Dedalus Labs",
      "Program / Role": "Product Manager Summer 2027 Intern",
      "Target Type": "Confirmed live startup PM internship",
      "Status": "Live",
      "Window / Deadline": "Live now; Summer 2027",
      "Location(s)": "San Francisco, CA",
      "Work Style": "In person",
      "Eligibility for You": "Eligible on school year: sophomore and above; non-CS backgrounds can apply, but technical fluency matters",
      "Degree / Major Notes": "Technical/CS background is preferred rather than presented as a hard degree gate",
      "Technical Knowledge Expected": "AI-agent infrastructure, developer tools, APIs/workflows, product specs, user research, product metrics; high technical fluency but not necessarily coding interview-level engineering",
      "Tech Bar (1-5)": 4,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 9.5,
      "Recruiting / Interview Notes": "Tiny team; evidence that you have built things is especially important. Dad Lore + LGO platform + hook dashboard are directly useful proof points.",
      "Compensation": "$4,000–$8,000/month; housing support where applicable",
      "Why It Fits You": "High-upside founder apprenticeship: direct founder/engineer/user exposure at a small AI-infrastructure startup, with explicit preference for builders and entrepreneurial experience.",
      "Immediate Next Action": "APPLY NOW — use builder/product resume and link strongest proof of work; prepare to discuss technical systems at a conceptual level.",
      "Human Check Needed": "Read the live application before submitting for any updated technical expectations or work-sample prompts.",
      "Official Source": "https://www.ycombinator.com/companies/dedalus-labs/jobs",
      "Secondary / Exact Posting": "https://www.dedaluslabs.ai/careers",
      "Last Verified": "2026-08-19",
      "Applications": [
        {
          "id": "dedalus-pm-2027",
          "title": "Product Manager Summer 2027 Intern",
          "roleStatus": "Live",
          "jobId": "Dedalus PM Summer 2027",
          "deadline": "Live now",
          "location": "San Francisco, CA",
          "workStyle": "In person",
          "compensation": "$4,000–$8,000/month; housing support",
          "url": "https://www.ycombinator.com/companies/dedalus-labs/jobs",
          "description": "PRODUCT MANAGER SUMMER 2027 INTERN\n\nABOUT DEDALUS LABS\nDedalus Labs is an early-stage San Francisco AI infrastructure company building compute and developer infrastructure for AI agents.\n\nRESPONSIBILITIES\n• Help shape product strategy for infrastructure and developer tools.\n• Write product specifications and feature requirements.\n• Conduct user research and customer discovery, including interviews with developers building and deploying AI agents.\n• Work with engineers to define APIs, workflows, and product behavior.\n• Design and improve onboarding and developer experience.\n• Prioritize improvements using customer feedback and usage data.\n• Define product metrics around activation, adoption, and retention.\n• Support product launches and feature validation from idea through production.\n• Improve internal tooling, documentation, and operational workflows.\n\nCORE QUALIFICATIONS\n• Sophomore or above.\n• Strong product intuition and user empathy.\n• Excellent written and verbal communication.\n• Ability to understand complex technical systems quickly.\n• Strong prioritization, problem solving, organization, proactivity, agency, and judgment.\n• Comfortable working closely with engineers and translating ambiguous ideas into concrete plans.\n\nNICE TO HAVE\nPrior startup/product/founder experience; evidence of building or shipping products; familiarity with developer tools, AI products, cloud infrastructure, Figma/Linear/Notion, user research, and product metrics. A CS/engineering background is listed as a preference rather than the only qualifying path.\n\nLOGISTICS\nSan Francisco, in person; Summer 2027; $4,000–$8,000/month; housing support where applicable. High-performing interns may receive full-time return offers.",
          "descriptionSource": "YC job board + current public posting details captured 2026-08-19",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 8,
      "Company": "Salesforce",
      "Program / Role": "Associate Product Manager (APM) Internship — Summer 2027",
      "Target Type": "Established APM internship",
      "Status": "Closed",
      "Window / Deadline": "Opened early July; 2027 internship deadline was July 24, 2026",
      "Location(s)": "San Francisco, CA",
      "Work Style": "TBD / role-specific",
      "Eligibility for You": "Was a relevant rising-senior APM target; now closed",
      "Degree / Major Notes": "Verify archived exact posting if needed",
      "Technical Knowledge Expected": "Product strategy, user needs, data, cross-functional work; AI product context; moderate technical fluency",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 0.0,
      "Recruiting / Interview Notes": "APM program has dedicated interview prep/Trailhead; exact closed 2027 process can be reviewed via program page",
      "Compensation": "Reported $55–$59/hour in 2027 posting",
      "Why It Fits You": "Excellent benchmark for the type of role you should target; unfortunately this cycle's internship closed",
      "Immediate Next Action": "No action for Summer 2027 unless it reopens; keep full-time APM on future list",
      "Human Check Needed": "You can manually inspect Salesforce APM program page and set alerts in case another APM internship requisition appears.",
      "Official Source": "https://www.salesforce.com/company/careers/university/associate-program-manager/",
      "Secondary / Exact Posting": "https://www.linkedin.com/jobs/view/summer-2027-intern-associate-product-manager-apm-at-salesforce-4440369294",
      "Last Verified": "2026-08-16",
      "Applications": [
        {
          "id": "salesforce-apm-2027",
          "title": "Associate Product Manager (APM) Internship — Summer 2027",
          "roleStatus": "Closed",
          "jobId": "Archived",
          "deadline": "Closed July 24, 2026",
          "location": "San Francisco, CA",
          "workStyle": null,
          "compensation": "Reported $55–$59/hour",
          "url": "https://www.salesforce.com/company/careers/university/associate-program-manager/",
          "description": "Summer 2027 Salesforce APM internship was a highly relevant early-career PM program but closed in July 2026. Keep this historical entry in the tracker for context and future full-time APM recruiting.",
          "descriptionSource": "Official/archived program status captured previously",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 9,
      "Company": "Duolingo",
      "Program / Role": "Associate Product Manager Internship",
      "Target Type": "APM target / monitor",
      "Status": "Opening soon",
      "Window / Deadline": "Duolingo says Product Management Thrive internships open in October yearly; standard APM timing should be rechecked when 2027 roles post",
      "Location(s)": "Pittsburgh, PA (historical/expected; verify exact 2027 posting)",
      "Work Style": "TBD",
      "Eligibility for You": "Potentially eligible; exact 2027 posting must be checked",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "Consumer product sense, experimentation, metrics, growth; technical fluency likely valued",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 8.1,
      "Recruiting / Interview Notes": "Expect product sense, analytics, behavioral; exact internship process TBD",
      "Compensation": "Secondary 2027 tracker estimate: ~$50–$52/hour for standard APM; verify official posting",
      "Why It Fits You": "Consumer app + experimentation culture; strong fit with your media/product instincts and love of user-facing ideas",
      "Immediate Next Action": "Prepare now; monitor Duolingo Careers through September/October and capture exact 2027 APM posting immediately when live.",
      "Human Check Needed": "Official Duolingo material confirms PM internships open in October yearly, but exact standard 2027 APM posting/deadline is not live yet.",
      "Official Source": "https://careers.duolingo.com/",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-19",
      "Applications": [
        {
          "id": "duolingo-apm-2027",
          "title": "Associate Product Manager Internship — Summer 2027",
          "roleStatus": "Opening soon",
          "jobId": "TBD",
          "deadline": "Expected fall 2026; exact deadline TBD",
          "location": "Pittsburgh, PA (expected)",
          "workStyle": "TBD",
          "compensation": "~$50–$52/hour secondary estimate; verify official",
          "url": "https://careers.duolingo.com/",
          "description": "Exact Summer 2027 posting is not live yet. Duolingo public internship materials say Product Management internships open in October yearly and emphasize ownership over experiments/features, use of user insights and data/statistics, and instinct for simple, intuitive user experiences. Full exact 2027 role description will be added when posted.",
          "descriptionSource": "Official Duolingo internship material + secondary tracker, verified 2026-08-19",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 10,
      "Company": "Airbnb",
      "Program / Role": "Product Management Internship",
      "Target Type": "Internship program / PM target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM role/window not verified today",
      "Location(s)": "TBD; verify internship posting",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; exact posting TBD",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "Consumer marketplace product, user research, metrics, experimentation, cross-functional execution; AI prototyping increasingly valued",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 6.1,
      "Recruiting / Interview Notes": "Likely product cases + analytical + behavioral; exact intern process TBD",
      "Compensation": "TBD",
      "Why It Fits You": "Exceptional founder apprenticeship in marketplace/product; strong ownership-path value",
      "Immediate Next Action": "Monitor Airbnb Internship Programs + job search for Product Manager Intern",
      "Human Check Needed": "The internship program is official, but no exact 2027 PM internship was verified today.",
      "Official Source": "https://careers.airbnb.com/internship-programs/",
      "Secondary / Exact Posting": "https://careers.airbnb.com/positions/8104444/",
      "Last Verified": "2026-08-16",
      "Applications": []
    },
    {
      "Rank": 11,
      "Company": "Roblox",
      "Program / Role": "Product Management Internship",
      "Target Type": "Early-career PM target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM requisition not verified today",
      "Location(s)": "San Mateo, CA expected/secondary tracker",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; verify exact posting",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "Consumer product, metrics, experimentation, platform thinking; technical understanding important",
      "Tech Bar (1-5)": 4,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 5.9,
      "Recruiting / Interview Notes": "Official early-career material includes product-management assessment categories; technical applications may receive coding assessments",
      "Compensation": "Secondary tracker estimate for expected PM intern: ~$62/hour; verify official posting",
      "Why It Fits You": "High-upside consumer platform; product judgment and young-user ecosystem exposure could be excellent founder prep",
      "Immediate Next Action": "Monitor Roblox Early Career jobs and search Product Manager Intern weekly",
      "Human Check Needed": "Official early-career page discusses PM assessments but does not currently expose a specific 2027 PM internship.",
      "Official Source": "https://careers.roblox.com/early-career",
      "Secondary / Exact Posting": "https://careers.roblox.com/interviewing-at-roblox",
      "Last Verified": "2026-08-19",
      "Applications": []
    },
    {
      "Rank": 12,
      "Company": "Adobe",
      "Program / Role": "Product Management / Product Internship",
      "Target Type": "University internship target",
      "Status": "Opening soon",
      "Window / Deadline": "Summer 2027 internships expected to roll out beginning early September; secondary tracker currently estimates roughly mid-September for a Product intern posting",
      "Location(s)": "Role-specific; secondary tracker currently surfaces Philadelphia for one Product internship",
      "Work Style": "Role-specific",
      "Eligibility for You": "Likely eligible for non-engineering product roles; exact posting decides",
      "Degree / Major Notes": "Role-specific",
      "Technical Knowledge Expected": "Product sense, creative/user workflows, AI/product judgment, analytics; technical bar varies",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 7.6,
      "Recruiting / Interview Notes": "Role-specific; likely recruiter + product/behavioral + analytical depending team",
      "Compensation": "Secondary tracker range for one expected Product internship: $45–$61/hour; verify official posting",
      "Why It Fits You": "Large product portfolio + generative AI + strong consumer/creator products; very good fit with your media/AI experimentation",
      "Immediate Next Action": "Keep materials ready; check Adobe Careers from early September and apply immediately to broad-major Product/PM roles.",
      "Human Check Needed": "Exact Product Management internship title, location and degree requirements are not yet published.",
      "Official Source": "https://careers.adobe.com/us/en/event/6a0ccc369c6fc67e77b1defb/The-Intern-Legacy",
      "Secondary / Exact Posting": "https://careers.adobe.com/us/en/university",
      "Last Verified": "2026-08-19",
      "Applications": [
        {
          "id": "adobe-summer-2027",
          "title": "Product Management / Product Internship",
          "roleStatus": "Opening soon",
          "jobId": "TBD",
          "deadline": "Summer 2027 internships expected to roll out beginning early September; secondary tracker currently estimates roughly mid-September for a Product intern posting",
          "location": "Role-specific; secondary tracker currently surfaces Philadelphia for one Product internship",
          "workStyle": "Role-specific",
          "compensation": "Secondary tracker range for one expected Product internship: $45–$61/hour; verify official posting",
          "url": "https://careers.adobe.com/us/en/event/6a0ccc369c6fc67e77b1defb/The-Intern-Legacy",
          "description": "Exact Summer 2027 role description has not been captured yet. Current tracker status: Opening soon.\n\nWhen the posting goes live, paste the full description into ChatGPT and regenerate data.js so this panel becomes the complete application record.",
          "descriptionSource": "Program/role tracking stub; exact posting pending",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 13,
      "Company": "American Express",
      "Program / Role": "2027 Undergraduate Product Internships (Digital Labs / GCS / ESS / Product Innovation)",
      "Target Type": "Confirmed live 2027 roles",
      "Status": "Live",
      "Window / Deadline": "Six verified NYC undergraduate product roles live; deadlines Sep. 30–Oct. 1, 2026",
      "Location(s)": "New York, NY",
      "Work Style": "Hybrid",
      "Eligibility for You": "Eligible: full-time Bachelor student graduating Dec. 2027–Jun. 2028; U.S. work authorization required",
      "Degree / Major Notes": "Broad-major friendly across most roles; USCS explicitly includes Economics; ESS lists business/technology/data/engineering/operations/risk or related",
      "Technical Knowledge Expected": "Varies by team: digital product, customer research, business cases, analytics, product backlogs, low-code/AI, payments; no universal coding requirement",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 8.4,
      "Recruiting / Interview Notes": "All six applications submitted. If contacted, tailor interview prep to division while keeping one core product/analytics/leadership story set.",
      "Compensation": "$24.05–$63/hour + sign-on bonus across the six NYC postings",
      "Why It Fits You": "Strong fintech/product brand, broad-major eligibility, and direct overlap with your analytics, experimentation, AI/no-code, cross-functional leadership, and consumer/business product work.",
      "Immediate Next Action": "Applied to all six. Monitor portal/email and prepare division-specific “why this product area” answers.",
      "Human Check Needed": "None for application eligibility; descriptions and job IDs captured individually below.",
      "Official Source": "https://careers.americanexpress.com/en/sites/CX_1/jobs?keyword=product+manager+intern&mode=location",
      "Secondary / Exact Posting": "https://careers.americanexpress.com/en/sites/CX_1/job/26011918/",
      "Last Verified": "2026-08-19",
      "Applications": [
        {
          "id": "26011918",
          "title": "2027 Digital Product — Amex Digital Labs",
          "roleStatus": "Live",
          "jobId": "26011918",
          "deadline": "2026-09-30 11:55 PM",
          "location": "New York, NY",
          "workStyle": "Hybrid",
          "compensation": "$24.05–$63/hour + sign-on bonus",
          "url": "https://careers.americanexpress.com/en/sites/CX_1/job/26011918",
          "description": "CAMPUS UNDERGRADUATE SUMMER INTERNSHIP PROGRAM — 2027 DIGITAL PRODUCT, AMEX DIGITAL LABS\n\nBUSINESS UNIT\nAmex Digital Labs catalyzes digital innovation by originating and scaling products and platforms relevant to customers' digital lives. The team works on digital payments and financial-services products, AI-powered customer-service solutions, and membership experiences, and collaborates with technology companies and strategic partners.\n\nROLE\nSummer Associate Digital Product Analyst intern. Own a project contributing to the launch or evolution of a digital initiative and contribute to product vision, strategy, and delivery. Product Managers identify customer needs, build experiences, and lead cross-company teams to launch digital products.\n\nREQUIRED\n• Full-time Bachelor's student.\n• Graduation date between December 2027 and June 2028.\n• U.S. work authorization; no sponsorship for this role.\n\nPREFERRED\n• Interest in fintech, emerging digital technologies, and customer-focused design.\n• Customer empathy and ability to use feedback in product decisions.\n• Growth mindset, curiosity, comfort with ambiguity, bias for action, adaptability.\n• Strong analytical and creative problem-solving skills and ability to derive insights from data.\n• Excellent written/verbal communication; translating technical requirements to non-technical audiences is a plus.\n\nJOB INFO\nJob ID 26011918 | Product | Posted Aug. 3, 2026 | Apply before Sep. 30, 2026 11:55 PM | New York, NY (Hybrid) | $24.05–$63/hour + sign-on bonus.",
          "descriptionSource": "User-pasted full posting captured 2026-08-19",
          "notes": ""
        },
        {
          "id": "26011916",
          "title": "2027 Product Management — Global Commercial Services",
          "roleStatus": "Live",
          "jobId": "26011916",
          "deadline": "2026-10-01 12:00 AM",
          "location": "New York, NY",
          "workStyle": "Hybrid",
          "compensation": "$24.05–$63/hour + sign-on bonus",
          "url": "https://careers.americanexpress.com/en/sites/CX_1/job/26011916",
          "description": "CAMPUS UNDERGRADUATE SUMMER INTERNSHIP PROGRAM — 2027 PRODUCT MANAGEMENT, GLOBAL COMMERCIAL SERVICES\n\nBUSINESS UNIT\nGlobal Commercial Services serves business customers from small businesses through Fortune 500 companies with cards, payments, cash-flow tools, working capital/supply-chain financing, and digital financial solutions.\n\nROLE\nProduct Management Intern. Own product strategy for a commercial product and contribute to identifying customer needs, building experiences, and managing/marketing products.\n\nRESPONSIBILITIES\n• Develop business cases for new products, features, and customer experiences.\n• Analyze customer feedback, market trends, and competitors to identify opportunities and inform product strategy.\n• Synthesize data, analytics, and financial insights into recommendations.\n• Support product-management processes including product backlogs, feature prioritization, and documentation of product/operational processes.\n• Collaborate with Marketing, Finance, Technology, Legal, Compliance, and other stakeholders.\n\nMINIMUM\n• Full-time Bachelor's student graduating December 2027–June 2028.\n• U.S. work authorization; no sponsorship.\n\nPREFERRED\n• Interest in commercial payments, digital products, and product management.\n• Strong analytical/problem-solving skills and ability to turn complexity into clear recommendations.\n• Curiosity about payments and emerging technology.\n• Strong relationship-building, project management, attention to detail, writing, and presentation.\n• Resilience, proactive mindset, and willingness to challenge the status quo.\n• Excel and PowerPoint proficiency.\n• Experience using AI tools such as ChatGPT or Copilot for research, analysis, problem solving, and productivity.\n\nJOB INFO\nJob ID 26011916 | Career Area: Product | Posted Aug. 3, 2026 | Apply before Oct. 1, 2026 | New York, NY (Hybrid) | $24.05–$63/hour + sign-on bonus.",
          "descriptionSource": "User-pasted full posting captured 2026-08-19",
          "notes": ""
        },
        {
          "id": "26012152",
          "title": "2027 Product Management — Global Merchant & Network Services",
          "roleStatus": "Live",
          "jobId": "26012152",
          "deadline": "2026-10-01 12:00 AM",
          "location": "New York, NY",
          "workStyle": "Hybrid",
          "compensation": "$24.05–$63/hour + sign-on bonus",
          "url": "https://careers.americanexpress.com/en/sites/CX_1/job/26012152",
          "description": "CAMPUS UNDERGRADUATE SUMMER INTERNSHIP PROGRAM — 2027 PRODUCT MANAGEMENT, GLOBAL MERCHANT & NETWORK SERVICES\n\nBUSINESS UNIT\nGlobal Merchant & Network Services manages American Express relationships with merchants that accept Amex, the payment network, and global bank/acceptance partners. The internship focuses on products and services that strengthen merchant value and grow the network.\n\nROLE\nAssociate Product Manager internship focused on end-to-end product lifecycle work.\n\nRESPONSIBILITIES\n• Contribute to product vision, strategy, and value proposition.\n• Understand customer pain points, journeys, and personas and articulate product value.\n• Conduct market/user research, identify trends, and evaluate the competitive landscape.\n• Develop quantitative and strategic business cases.\n• Collect and synthesize product data into actionable insights that steer strategy.\n• Partner with Delivery and Technology teams to groom, prioritize, and execute the product backlog in an agile environment.\n• Drive feature/product adoption and engagement, support marketing/servicing materials, and measure post-launch impact.\n• Collaborate with engineering, data, analytics, product, and other internal/external stakeholders.\n\nMINIMUM\n• Full-time Bachelor's student graduating December 2027–June 2028.\n• U.S. work authorization; no sponsorship.\n\nPREFERRED\n• Interest in payments, digital products, and product management.\n• Strong analytical/problem-solving and ability to distill complex issues.\n• Intellectual curiosity about payments and emerging technology.\n• Strong collaboration, writing, speaking, project management, and attention to detail.\n• Ability to translate data/insights into business opportunities.\n• Excel and PowerPoint proficiency.\n• Payments experience and SQL/Hive are pluses, not requirements.\n\nJOB INFO\nJob ID 26012152 | Product | Posted Aug. 5, 2026 | Apply before Oct. 1, 2026 | New York, NY (Hybrid) | $24.05–$63/hour + sign-on bonus.",
          "descriptionSource": "User-pasted full posting captured 2026-08-19",
          "notes": ""
        },
        {
          "id": "26012174",
          "title": "2027 Product Development — U.S. Consumer Services",
          "roleStatus": "Live",
          "jobId": "26012174",
          "deadline": "2026-10-01 12:00 AM",
          "location": "New York, NY",
          "workStyle": "Hybrid",
          "compensation": "$24.05–$63/hour + sign-on bonus",
          "url": "https://careers.americanexpress.com/en/sites/CX_1/job/26012174",
          "description": "CAMPUS UNDERGRADUATE SUMMER INTERNSHIP PROGRAM — 2027 PRODUCT DEVELOPMENT, U.S. CONSUMER SERVICES\n\nBUSINESS UNIT\nU.S. Consumer Services treats Membership as the core product, spanning premium/cobrand/cash-back/lending cards, Membership Rewards, Travel & Lifestyle Services, Centurion Lounges, Global Dining, U.S. Consumer Banking, Amex Offers, Amex Ads, and related marketing programs.\n\nROLE / RESPONSIBILITIES\nProduct Development intern supporting critical and innovative projects. Own a project contributing to the launch or evolution of a card, lending, or membership service (such as travel or dining). Contribute to product vision, strategy, and digital-product delivery. Product Managers identify customer needs, build experiences, and lead cross-company teams to launch products and partner experiences.\n\nMINIMUM\n• Bachelor's student in Business Administration, Marketing, Economics, Finance, Product Management, Systems Engineering, or related field.\n• Graduation date December 2027–June 2028.\n• U.S. work authorization; no sponsorship.\n\nPREFERRED\n• Interest in card, lending, or membership products such as travel/dining.\n• Growth mindset and ability to solve problems beyond the obvious.\n• Empathy for diverse users.\n• Curiosity, flexibility, comfort with ambiguity, and receptiveness to feedback.\n• Strong analytical and decision-making skills; ability to compile, analyze, research, and connect complex issues.\n• Willingness to roll up sleeves and execute.\n\nJOB INFO\nJob ID 26012174 | Product | Posted Aug. 4, 2026 | Apply before Oct. 1, 2026 | New York, NY (Hybrid) | $24.05–$63/hour + sign-on bonus.",
          "descriptionSource": "User-pasted full posting captured 2026-08-19",
          "notes": ""
        },
        {
          "id": "26011992",
          "title": "2027 Product Innovation — Credit & Fraud Risk",
          "roleStatus": "Live",
          "jobId": "26011992",
          "deadline": "2026-09-30 1:00 AM",
          "location": "New York, NY",
          "workStyle": "Hybrid",
          "compensation": "$24.05–$63/hour + sign-on bonus",
          "url": "https://careers.americanexpress.com/en/sites/CX_1/job/26011992",
          "description": "CAMPUS UNDERGRADUATE SUMMER INTERNSHIP PROGRAM — 2027 PRODUCT INNOVATION, CREDIT & FRAUD RISK\n\nBUSINESS UNIT\nCredit & Fraud Risk combines risk strategy, technology, infrastructure, and computing techniques to make credit/fraud decisions and improve customer communication and servicing. The Risk Products team turns risk strategies into customer-focused capabilities.\n\nRESPONSIBILITIES\n• Help define product vision and roadmaps and communicate with stakeholders.\n• Support next-generation software products solving risk-management needs.\n• Collaborate with risk, technology, and product teams to build and iterate products used by customers/prospects.\n• Support global/reusable/configurable product design, prioritization, feature development, testing, integration, and launch using low-code tools.\n• Coordinate cross-functional calls to define features, user stories, and business requirements.\n• Host stand-ups with technology partners and help resolve development issues.\n• Analyze product performance and make data-driven recommendations for future state.\n• Create decks, product-requirement documentation, status updates, presentations, and reports.\n• Potential projects include reusable components, pain-point elimination, and product-delivery process optimization.\n\nMINIMUM\n• Full-time Bachelor's student graduating December 2027–June 2028.\n• U.S. work authorization; no sponsorship.\n\nPREFERRED\n• Interest in digital technology and customer-driven design.\n• Independent, organized, detail-oriented, and able to multitask.\n• Strong analytical/quantitative problem solving.\n• Willingness to experiment and share fresh perspectives.\n• Excel/PowerPoint proficiency and strong communication.\n\nJOB INFO\nJob ID 26011992 | Career Area: Product | Posted Aug. 3, 2026 | Apply before Sep. 30, 2026 | New York, NY (Hybrid) | $24.05–$63/hour + sign-on bonus.",
          "descriptionSource": "User-pasted full posting captured 2026-08-19",
          "notes": ""
        },
        {
          "id": "26012228",
          "title": "2027 Product & Capabilities — Enterprise Shared Services",
          "roleStatus": "Live",
          "jobId": "26012228",
          "deadline": "2026-09-30 1:00 AM",
          "location": "New York, NY",
          "workStyle": "Hybrid",
          "compensation": "$24.05–$63/hour + sign-on bonus",
          "url": "https://careers.americanexpress.com/en/sites/CX_1/job/26012228",
          "description": "CAMPUS UNDERGRADUATE SUMMER INTERNSHIP PROGRAM — 2027 PRODUCT & CAPABILITIES, ENTERPRISE SHARED SERVICES\n\nBUSINESS UNIT\nEnterprise Shared Services includes functions central to company operations such as real estate/workplace, supply management, business resilience/governance, aviation, internal fraud, and security. The Product & Capabilities internship spans products, platforms, reporting, governance, process improvement, and technology enablement, including GenAI, intelligent automation, and advanced analytics.\n\nRESPONSIBILITIES\n• Support cross-functional product/capability projects across business, technology, and end users.\n• Gather and document business requirements, user needs, process flows, project updates, and translate them into technical requirements.\n• Contribute to roadmaps, implementation, adoption, and performance measurement.\n• Analyze data and prepare reports, presentations, dashboards, and insights.\n• Identify GenAI, intelligent-automation, and analytics opportunities to improve workflows and colleague experience.\n• Support design, testing, and rollout of secure, scalable solutions.\n• Participate in process-improvement work across productivity, efficiency, quality, risk, and controls.\n• Work in a complex matrixed organization and gain exposure to Agile methods.\n\nMINIMUM\n• Full-time Bachelor's student graduating December 2027–June 2028.\n• Degree in business, technology, data analytics, computer science, engineering, operations, risk management, or related field.\n• Interest in product, technology, operations, process improvement, analytics, or AI.\n• Strong analytical/problem-solving, communication, collaboration, prioritization, and attention to detail.\n• Excel and PowerPoint proficiency.\n• U.S. work authorization; no sponsorship.\n\nPREFERRED\nCoursework/projects in data, AI, automation, agile, or digital products; experience with Tableau, Power BI, ServiceNow, Archer, or similar; ability to connect project work to business outcomes; interest in responsible AI innovation and governance.\n\nJOB INFO\nJob ID 26012228 | Career Area: Product | Posted Aug. 5, 2026 | Apply before Sep. 30, 2026 | New York, NY (Hybrid) | $24.05–$63/hour + sign-on bonus.",
          "descriptionSource": "User-pasted full posting captured 2026-08-19",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 14,
      "Company": "PayPal",
      "Program / Role": "Product Management Summer Internship",
      "Target Type": "North America university internship",
      "Status": "Monitor",
      "Window / Deadline": "US/Canada recruitment season runs August–March; applications considered on an ongoing basis",
      "Location(s)": "San Jose, CA expected/secondary tracker; exact 2027 PM posting not live",
      "Work Style": "Role-specific / relocation unless specified otherwise",
      "Eligibility for You": "Likely eligible: must return to school after internship and have work authorization",
      "Degree / Major Notes": "Exact PM posting decides",
      "Technical Knowledge Expected": "Payments/fintech product, analytics, customer experience, cross-functional execution; technical depth role-specific",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.8,
      "Recruiting / Interview Notes": "Role-specific; likely recruiter + product/behavioral/analytics",
      "Compensation": "Secondary tracker historical/expected band: $21–$55/hour; verify official posting",
      "Why It Fits You": "Excellent non-CS PM path with fintech exposure; close to both product-building and business economics",
      "Immediate Next Action": "Search PayPal jobs for Product Management + Internship now and check weekly through fall",
      "Human Check Needed": "Official university page confirms Product Management is an internship area and season is Aug–Mar, but exact 2027 US PM requisition needs manual search.",
      "Official Source": "https://careers.pypl.com/university-hiring/north-america-latin-america/default.aspx",
      "Secondary / Exact Posting": "https://careers.pypl.com/categories/product-management/",
      "Last Verified": "2026-08-19",
      "Applications": []
    },
    {
      "Rank": 15,
      "Company": "Figma",
      "Program / Role": "Product Management Internship",
      "Target Type": "High-upside watchlist employer",
      "Status": "Monitor",
      "Window / Deadline": "No Summer 2027 PM internship verified today",
      "Location(s)": "TBD; check live posting",
      "Work Style": "TBD",
      "Eligibility for You": "Unknown until posting exists",
      "Degree / Major Notes": "Unknown",
      "Technical Knowledge Expected": "Product craft, design collaboration, user research, technical fluency, SaaS/creator workflows",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 6.1,
      "Recruiting / Interview Notes": "Likely product sense + craft + behavioral/analytical; exact internship process unknown",
      "Compensation": "TBD",
      "Why It Fits You": "World-class product culture and founder-relevant product craft; especially attractive if a non-CS PM intern opens",
      "Immediate Next Action": "Monitor Figma careers; search 'Product' + 'Intern' and set alert",
      "Human Check Needed": "Current early-career openings did not show a PM internship. If you see one in the browser, send it to me immediately.",
      "Official Source": "https://www.figma.com/careers/",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16",
      "Applications": []
    },
    {
      "Rank": 16,
      "Company": "Notion",
      "Program / Role": "Product Management Internship",
      "Target Type": "High-upside watchlist employer",
      "Status": "Monitor",
      "Window / Deadline": "No Summer 2027 PM internship verified today",
      "Location(s)": "TBD; exact internship location TBD",
      "Work Style": "Role-specific",
      "Eligibility for You": "Unknown until posting exists",
      "Degree / Major Notes": "Unknown",
      "Technical Knowledge Expected": "Product craft, workflow design, AI, qualitative user judgment, metrics; technical fluency valuable",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 6.1,
      "Recruiting / Interview Notes": "Likely product sense + execution/behavioral; exact internship process unknown",
      "Compensation": "TBD",
      "Why It Fits You": "Very strong founder/product apprenticeship if an intern role exists; directly aligned with your interest in tools/AI/workflows",
      "Immediate Next Action": "Monitor Notion careers for Product/PM internship; do not assume they run one every year",
      "Human Check Needed": "Official careers page currently shows early-career technical roles but no verified PM internship.",
      "Official Source": "https://www.notion.com/careers",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16",
      "Applications": []
    },
    {
      "Rank": 17,
      "Company": "Intuit",
      "Program / Role": "Rotational Product Management (RPM) Internship — Summer 2027",
      "Target Type": "Established RPM internship",
      "Status": "Opening soon",
      "Window / Deadline": "Official RPM page: Summer 2027 internship applications expected to open September 2026",
      "Location(s)": "Mountain View, CA",
      "Work Style": "Hybrid / co-located",
      "Eligibility for You": "Eligible: student with at least one semester remaining after internship",
      "Degree / Major Notes": "Open to candidates from varied backgrounds; no CS-major gate stated on program page",
      "Technical Knowledge Expected": "Customer discovery, experimentation, AI/ML product thinking, requirements, metrics, cross-functional execution",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 10,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 8.8,
      "Recruiting / Interview Notes": "Small, established RPM cohort; official page recommends PM interview preparation and emphasizes entrepreneurial/customer-obsessed product thinking.",
      "Compensation": "TBD for Summer 2027 exact posting",
      "Why It Fits You": "Excellent non-CS-friendly PM training in fintech/small-business products, with explicit experimentation, AI, customer research, and entrepreneurial mindset.",
      "Immediate Next Action": "PREPARE FOR SEPTEMBER — set alert and have application materials ready to submit when the exact 2027 internship opens.",
      "Human Check Needed": "Exact requisition, deadline, and compensation are not live yet; update immediately when posted.",
      "Official Source": "https://talenteq.intuit.com/rotational-product-management-program",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-19",
      "Applications": [
        {
          "id": "intuit-rpm-2027",
          "title": "Rotational Product Management Internship — Summer 2027",
          "roleStatus": "Opening soon",
          "jobId": "TBD",
          "deadline": "Expected September 2026",
          "location": "Mountain View, CA",
          "workStyle": "Hybrid / co-located",
          "compensation": "TBD",
          "url": "https://talenteq.intuit.com/rotational-product-management-program",
          "description": "ROTATIONAL PRODUCT MANAGEMENT (RPM) SUMMER 2027 INTERNSHIP — PROGRAM PREVIEW\n\nThe exact Summer 2027 requisition is not yet live. Intuit's official RPM program page says applications are expected to open in September 2026.\n\nPROGRAM\nThe RPM program is designed for early-career product talent and emphasizes customer obsession, rapid experimentation, technical/product depth, AI/ML-enabled experiences, cross-functional collaboration, and entrepreneurial ownership. RPM interns work on real customer problems and receive structured PM training and mentorship.\n\nELIGIBILITY\nRPM interns must have at least one semester of university remaining after the internship.\n\nLOCATION\nAll RPM interns are assigned to Mountain View, California on a hybrid basis; relocation stipend is available for interns who relocate.\n\nTIMING\nSummer internship is typically 12 weeks. Exact 2027 role title, compensation, and application deadline will be added when the requisition opens.",
          "descriptionSource": "Official Intuit RPM program page captured 2026-08-19",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 18,
      "Company": "Spotify",
      "Program / Role": "Global Summer Internship — Product / Product Management",
      "Target Type": "Global internship program",
      "Status": "Monitor",
      "Window / Deadline": "2027 application dates not published; 2026 cycle is closed",
      "Location(s)": "New York, NY expected/secondary tracker; exact 2027 posting not live",
      "Work Style": "Role-specific",
      "Eligibility for You": "Likely eligible as penultimate-year student when 2027 opens; exact role TBD",
      "Degree / Major Notes": "Role-specific",
      "Technical Knowledge Expected": "Consumer product sense, experimentation, user/creator empathy, metrics, cross-functional leadership",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Role-specific; expect product/analytics/behavioral for PM-type roles",
      "Compensation": "TBD",
      "Why It Fits You": "Excellent consumer product training and brand; highly relevant to your media/product instincts",
      "Immediate Next Action": "Monitor Students page; Spotify does not accept late applications, so apply within the published window",
      "Human Check Needed": "Official Students page currently only states that 2026 applications are closed; 2027 dates are not yet posted.",
      "Official Source": "https://www.lifeatspotify.com/start-your-journey/students",
      "Secondary / Exact Posting": "https://www.lifeatspotify.com/find-your-team/job-categories/product",
      "Last Verified": "2026-08-19",
      "Applications": []
    },
    {
      "Rank": 19,
      "Company": "Capital One",
      "Program / Role": "Product Development Internship Program (PDP)",
      "Target Type": "Established product internship",
      "Status": "Closed",
      "Window / Deadline": "2027 Product Development internship not currently listed; prior cycle appears to have closed",
      "Location(s)": "US role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "General internship eligibility supports students graduating by Aug 2028; exact PDP cycle closed/not listed",
      "Degree / Major Notes": "Economics is explicitly recognized as quantitative/STEM-related for some product early-career programs",
      "Technical Knowledge Expected": "Product strategy, business/analytics, customer problems; low coding requirement relative to technical PM",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 9,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 0.0,
      "Recruiting / Interview Notes": "Typically case/product-style and behavioral; exact 2027 closed-process details should be checked if it reopens",
      "Compensation": "TBD",
      "Why It Fits You": "One of the best non-CS product programs for you: analytical/business PM with strong training",
      "Immediate Next Action": "Set Capital One job alert; watch for a reopen or location-specific PDP requisition",
      "Human Check Needed": "Official internship page does not currently list the Product Development Internship. If your browser/Handshake shows a live PDP link, send it to me.",
      "Official Source": "https://www.capitalonecareers.com/internship-programs",
      "Secondary / Exact Posting": "https://www.capitalonecareers.com/get-ahead-with-early-career-programs-for-students",
      "Last Verified": "2026-08-16",
      "Applications": []
    },
    {
      "Rank": 20,
      "Company": "Dropbox",
      "Program / Role": "Product Management Internship",
      "Target Type": "Emerging talent / PM watchlist",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM opening/window not verified today; general internship is 12 weeks",
      "Location(s)": "Remote in USA (secondary tracker; exact 2027 posting not live)",
      "Work Style": "Virtual First company model; intern specifics vary",
      "Eligibility for You": "Potentially eligible; exact role TBD",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "SaaS/product craft, collaboration, metrics, user workflows; technical fluency helpful",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.3,
      "Recruiting / Interview Notes": "Role-specific; likely product/behavioral/analytics",
      "Compensation": "TBD",
      "Why It Fits You": "Good PM craft + modern SaaS environment; flexible location can be attractive",
      "Immediate Next Action": "Monitor Emerging Talent and search Product + Intern",
      "Human Check Needed": "Official emerging-talent page confirms internship program but no exact 2027 PM requisition was verified today.",
      "Official Source": "https://www.dropbox.jobs/en/emerging-talent/",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-19",
      "Applications": []
    },
    {
      "Rank": 21,
      "Company": "IBM",
      "Program / Role": "Product Manager Intern 2027",
      "Target Type": "Confirmed live role — details partly blocked",
      "Status": "Monitor",
      "Window / Deadline": "Current secondary PM tracker does not show a live 2027 PM intern requisition; continue checking IBM official careers",
      "Location(s)": "Austin + other locations historically surfaced; exact 2027 role TBD",
      "Work Style": "HUMAN VERIFY",
      "Eligibility for You": "Likely relevant, but exact degree/eligibility details need manual inspection",
      "Degree / Major Notes": "Official page is JS/anti-bot blocked; inspect exact education/technical requirements yourself",
      "Technical Knowledge Expected": "AI-enabled/data-driven software, research, experimentation, prioritization, stakeholder collaboration",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 7.0,
      "Recruiting / Interview Notes": "Likely PM/product + behavioral + analytical; exact process TBD",
      "Compensation": "Secondary historical range: $33.17–$60.82/hour; verify exact future posting",
      "Why It Fits You": "Real live 2027 PM title at a major tech company; could be a very good non-obvious option if no CS-major gate",
      "Immediate Next Action": "Monitor IBM Careers for Product Manager Intern 2027 and re-verify if the requisition reappears.",
      "Human Check Needed": "Earlier exact role was surfaced but current live tracker no longer shows it open; do not assume the old link remains active.",
      "Official Source": "https://careers.ibm.com/en_US/careers/JobDetail/Product-Manager-Intern-2027/128509",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-19",
      "Applications": []
    },
    {
      "Rank": 22,
      "Company": "Mastercard",
      "Program / Role": "Product Management Internship",
      "Target Type": "Global internship / product target",
      "Status": "Monitor",
      "Window / Deadline": "Internships recruited on a rolling basis; exact US 2027 PM requisition not verified today",
      "Location(s)": "New York, NY expected/secondary tracker; exact 2027 posting not live",
      "Work Style": "Role-specific",
      "Eligibility for You": "Likely eligible as enrolled Bachelor's student; exact role decides",
      "Degree / Major Notes": "Generally business/product friendly; exact major TBD",
      "Technical Knowledge Expected": "Payments product, business cases, roadmaps, launch, analytics; limited coding likely for business PM",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Role-specific; likely behavioral + product/business case",
      "Compensation": "TBD",
      "Why It Fits You": "Payments + product is useful for both founder skills and financial-system understanding",
      "Immediate Next Action": "Search Mastercard Product Management jobs + Internship + United States now; check regularly because rolling",
      "Human Check Needed": "Official internship and PM pages exist, but the exact Summer 2027 US PM role needs manual job search.",
      "Official Source": "https://careers.mastercard.com/us/en/early-careers/internships",
      "Secondary / Exact Posting": "https://careers.mastercard.com/us/en/c/product-management-jobs",
      "Last Verified": "2026-08-19",
      "Applications": []
    },
    {
      "Rank": 23,
      "Company": "eBay",
      "Program / Role": "Product Management Internship",
      "Target Type": "Emerging talent / marketplace PM target",
      "Status": "Opening soon",
      "Window / Deadline": "Internship roles are posted September through March",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; exact 2027 PM posting TBD",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "Marketplace product, growth, seller/buyer experience, analytics, experimentation",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 7.0,
      "Recruiting / Interview Notes": "Role-specific; likely product + analytics + behavioral",
      "Compensation": "TBD",
      "Why It Fits You": "Marketplace PM is founder-relevant and fits your interest in consumer products and business models",
      "Immediate Next Action": "Start checking in early September; set eBay Emerging Talent alert",
      "Human Check Needed": "Official page gives posting season but not a live 2027 PM requisition yet.",
      "Official Source": "https://jobs.ebayinc.com/us/en/emerging-talent",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16",
      "Applications": [
        {
          "id": "ebay-summer-2027",
          "title": "Product Management Internship",
          "roleStatus": "Opening soon",
          "jobId": "TBD",
          "deadline": "Internship roles are posted September through March",
          "location": "Role-specific",
          "workStyle": "Role-specific",
          "compensation": "TBD",
          "url": "https://jobs.ebayinc.com/us/en/emerging-talent",
          "description": "Exact Summer 2027 role description has not been captured yet. Current tracker status: Opening soon.\n\nWhen the posting goes live, paste the full description into ChatGPT and regenerate data.js so this panel becomes the complete application record.",
          "descriptionSource": "Program/role tracking stub; exact posting pending",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 24,
      "Company": "Lyft",
      "Program / Role": "Product Management Internship",
      "Target Type": "Early talent / marketplace PM target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM opening/window not verified today",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; exact posting TBD",
      "Degree / Major Notes": "TBD",
      "Technical Knowledge Expected": "Marketplace product, rider/driver problems, experimentation, metrics, operations + product",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Role-specific; likely product case + metrics + behavioral",
      "Compensation": "TBD",
      "Why It Fits You": "Strong marketplace/founder training; your operations background could translate well",
      "Immediate Next Action": "Monitor Lyft Early Talent and Product job filters",
      "Human Check Needed": "Official early-talent page is live, but no exact 2027 PM intern posting was verified today.",
      "Official Source": "https://www.lyft.com/careers/early-talent",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-16",
      "Applications": []
    },
    {
      "Rank": 25,
      "Company": "Reddit",
      "Program / Role": "Product Management Internship",
      "Target Type": "Consumer product watchlist",
      "Status": "Monitor",
      "Window / Deadline": "Current Summer 2027 PM role not verified; Reddit has historically run PM internships",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Unknown until role appears",
      "Degree / Major Notes": "TBD",
      "Technical Knowledge Expected": "Community product, moderation/growth, experimentation, metrics, qualitative user behavior",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Likely product sense + analytics + behavioral",
      "Compensation": "TBD",
      "Why It Fits You": "Consumer/community product is a natural fit with Dad Lore and your interest in social products",
      "Immediate Next Action": "Monitor Reddit careers for Product + Intern; do not assume a PM internship will exist this cycle",
      "Human Check Needed": "Current careers page is source of truth; historical PM internship existence does not guarantee a 2027 opening.",
      "Official Source": "https://redditinc.com/careers",
      "Secondary / Exact Posting": "https://redditinc.com/news/announcing-season-2-of-reddits-internship-program",
      "Last Verified": "2026-08-16",
      "Applications": []
    },
    {
      "Rank": 26,
      "Company": "Walmart",
      "Program / Role": "Product Management Internship",
      "Target Type": "Undergraduate internship / product target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM role/window not verified today",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; official student site includes Product Management as a career area",
      "Degree / Major Notes": "TBD by posting",
      "Technical Knowledge Expected": "Large-scale commerce product, customer/associate tools, data, roadmap prioritization",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Role-specific; likely behavioral + product/business case",
      "Compensation": "TBD",
      "Why It Fits You": "Massive real-world product scale and commerce economics; less glamorous but strong operating training",
      "Immediate Next Action": "Use Walmart Students → Product Management → See opportunities; filter internships",
      "Human Check Needed": "Product Management is explicitly shown as a student career area, but exact 2027 requisition must be found manually.",
      "Official Source": "https://careers.walmart.com/us/en/home/careers-areas/students",
      "Secondary / Exact Posting": "https://careers.walmart.com/us/en/home/careers-areas/technology/product-management",
      "Last Verified": "2026-08-16",
      "Applications": []
    },
    {
      "Rank": 27,
      "Company": "ServiceNow",
      "Program / Role": "Product Management Internship",
      "Target Type": "Early careers / enterprise product target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM requisition not verified today",
      "Location(s)": "Role-specific",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; exact posting TBD",
      "Degree / Major Notes": "Role-specific; technical depth can vary",
      "Technical Knowledge Expected": "Enterprise SaaS, AI/workflows, roadmap, customer problems, technical fluency",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.3,
      "Recruiting / Interview Notes": "Role-specific; likely product + behavioral + technical fluency",
      "Compensation": "TBD",
      "Why It Fits You": "Good enterprise SaaS/AI product apprenticeship; useful if you want to learn B2B software economics",
      "Immediate Next Action": "Search ServiceNow jobs with Posting Type Intern + AI/Engineering/Product",
      "Human Check Needed": "Official early-careers page confirms internships but no exact PM 2027 role was verified today.",
      "Official Source": "https://careers.servicenow.com/early-careers/",
      "Secondary / Exact Posting": "https://careers.servicenow.com/jobs/",
      "Last Verified": "2026-08-16",
      "Applications": []
    },
    {
      "Rank": 28,
      "Company": "Snap",
      "Program / Role": "Product Management Internship",
      "Target Type": "Emerging talent / consumer product target",
      "Status": "Monitor",
      "Window / Deadline": "No current US Product intern verified today",
      "Location(s)": "New York, NY expected/secondary tracker; exact 2027 posting not live",
      "Work Style": "Role-specific",
      "Eligibility for You": "Unknown until posting exists",
      "Degree / Major Notes": "TBD",
      "Technical Knowledge Expected": "Consumer social product, experimentation, growth, creator/advertiser ecosystems, metrics",
      "Tech Bar (1-5)": 3,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 9,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Likely product sense + analytics + behavioral",
      "Compensation": "TBD",
      "Why It Fits You": "Strong consumer/social product training; directly adjacent to the kinds of products you like experimenting with",
      "Immediate Next Action": "Monitor Snap Emerging Talent; filter live jobs for Product + Intern weekly",
      "Human Check Needed": "Current job board did not show a US PM intern at verification time.",
      "Official Source": "https://careers.snap.com/emerging-talent",
      "Secondary / Exact Posting": "https://careers.snap.com/jobs",
      "Last Verified": "2026-08-19",
      "Applications": []
    },
    {
      "Rank": 29,
      "Company": "Visa",
      "Program / Role": "Product Management Internship",
      "Target Type": "Early careers / fintech product target",
      "Status": "Monitor",
      "Window / Deadline": "Exact Summer 2027 PM role/window not verified today",
      "Location(s)": "San Mateo, CA expected/secondary tracker; exact 2027 posting not live",
      "Work Style": "Role-specific",
      "Eligibility for You": "Potentially eligible; exact posting TBD",
      "Degree / Major Notes": "Generally product/business friendly; exact major TBD",
      "Technical Knowledge Expected": "Payments/network product, business cases, analytics, customer solutions, roadmap",
      "Tech Bar (1-5)": 2,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 8,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 5.5,
      "Recruiting / Interview Notes": "Role-specific; likely behavioral + business/product case",
      "Compensation": "TBD",
      "Why It Fits You": "Strong payments infrastructure exposure; useful business/product skillset even if less startup-like",
      "Immediate Next Action": "Search Visa jobs for Product Management + Intern + United States; create alert",
      "Human Check Needed": "Official early-career page exists, but exact 2027 PM posting must be located manually.",
      "Official Source": "https://corporate.visa.com/en/careers/early-careers.html",
      "Secondary / Exact Posting": "https://corporate.visa.com/en/jobs/",
      "Last Verified": "2026-08-19",
      "Applications": []
    },
    {
      "Rank": 30,
      "Company": "Databricks",
      "Program / Role": "Product Management Intern — Summer 2027",
      "Target Type": "Confirmed live 2027 role",
      "Status": "Live — likely ineligible",
      "Window / Deadline": "Live now",
      "Location(s)": "San Francisco / Mountain View, CA; Bellevue, WA",
      "Work Style": "Role-specific",
      "Eligibility for You": "Likely ineligible for you",
      "Degree / Major Notes": "Requires Bachelor's/Master's in Computer Science or related engineering; Fall 2027/Spring 2028 graduation",
      "Technical Knowledge Expected": "SQL/Python, AI tools, technical product, data/AI platform knowledge",
      "Tech Bar (1-5)": 5,
      "Competitiveness (1-5)": 5,
      "User Fit (1-10)": 4,
      "Ownership / Wealth Value (1-10)": 10,
      "Action Score": 0.0,
      "Recruiting / Interview Notes": "Technical/product interviews likely; exact process role-specific",
      "Compensation": "Bay Area $54–$56/hour; Bellevue $51.50–$53.50/hour",
      "Why It Fits You": "Elite PM training, but this exact posting's degree requirement is a hard mismatch with Econ/Philosophy",
      "Immediate Next Action": "Do NOT spend time applying unless the degree requirement changes or recruiter confirms your degree qualifies",
      "Human Check Needed": "You can read the degree requirement directly on the official posting.",
      "Official Source": "https://www.databricks.com/company/careers/product/product-management-intern-summer-2027-6883068002",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-19",
      "Applications": [
        {
          "id": "6883068002",
          "title": "Product Management Intern — Summer 2027",
          "roleStatus": "Live — likely ineligible",
          "jobId": "6883068002",
          "deadline": "Live now",
          "location": "San Francisco / Mountain View, CA; Bellevue, WA",
          "workStyle": null,
          "compensation": "Bay Area $54–$56/hour; Bellevue $51.50–$53.50/hour",
          "url": "https://www.databricks.com/company/careers/product/product-management-intern-summer-2027-6883068002",
          "description": "Live Summer 2027 Product Management internship. Exact posting requires a Bachelor’s/Master’s in Computer Science or a related engineering field and expects SQL/Python plus technical data/AI product fluency, making this a poor-fit application for an Economics/Philosophy profile unless Databricks confirms the degree requirement can be waived.",
          "descriptionSource": "Official Databricks posting previously verified; refreshed 2026-08-19",
          "notes": ""
        }
      ]
    },
    {
      "Rank": 31,
      "Company": "Appian",
      "Program / Role": "Product Manager Intern — Summer 2027",
      "Target Type": "Confirmed live 2027 role",
      "Status": "Live — likely ineligible",
      "Window / Deadline": "Live; recruiting/interview scheduling begins Aug 2026",
      "Location(s)": "McLean, VA",
      "Work Style": "Role-specific",
      "Eligibility for You": "Likely ineligible for you",
      "Degree / Major Notes": "Requires Bachelor's/Master's in Computer Science or Computer Engineering",
      "Technical Knowledge Expected": "AI/LLM fluency, technical product, software concepts; technical internship/projects preferred",
      "Tech Bar (1-5)": 5,
      "Competitiveness (1-5)": 4,
      "User Fit (1-10)": 3,
      "Ownership / Wealth Value (1-10)": 8,
      "Action Score": 0.0,
      "Recruiting / Interview Notes": "Product + technical interviews likely",
      "Compensation": "$50/hour (~$8,666/month)",
      "Why It Fits You": "Good PM role, but exact degree gate makes it a poor use of your time",
      "Immediate Next Action": "Skip unless recruiter explicitly says non-CS majors may apply",
      "Human Check Needed": "Degree requirement is explicit on official job posting.",
      "Official Source": "https://careers.appian.com/jobs/8041243-product-manager-intern-",
      "Secondary / Exact Posting": null,
      "Last Verified": "2026-08-19",
      "Applications": [
        {
          "id": "8041243",
          "title": "Product Manager Intern — Summer 2027",
          "roleStatus": "Live — likely ineligible",
          "jobId": "8041243",
          "deadline": "Live now",
          "location": "McLean, VA",
          "workStyle": null,
          "compensation": "$50/hour (~$8,666/month)",
          "url": "https://careers.appian.com/jobs/8041243-product-manager-intern-",
          "description": "Live Product Manager Intern role, but the posting explicitly requires a Bachelor’s/Master’s in Computer Science or Computer Engineering and emphasizes AI/LLM and software concepts. Keep for market awareness; do not spend time applying unless a recruiter confirms non-CS majors can qualify.",
          "descriptionSource": "Official Appian posting previously verified; refreshed 2026-08-19",
          "notes": ""
        }
      ]
    }
  ],
  "notes": [
    "Applications are now tracked individually inside each company/target.",
    "Full role descriptions are stored on exact application records when captured.",
    "Personal progress remains browser-local and is not published in data.js.",
    "Open-status web refresh completed 2026-08-19; official company sources override secondary opening estimates."
  ]
};
